import fs from 'node:fs';
import {strict as assert} from 'node:assert';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
const fixture=createCatalogFixture(),sqlite=fixture.sqlite;
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};
const routeNames=['library','lists','views','library/import','catalog','games'];
const modules={};for(const name of routeNames)modules[name]=await moduleFor('app/api/'+name+'/route.ts',{auth:true});
await readyCatalog(await moduleFor('lib/catalog-bootstrap.ts'));
const catalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));const id=catalog.find(x=>x.name==='Kenshi').id;const req=(p,b,method='POST',origin='https://test.example')=>new Request('https://test.example/api/'+p,{method,headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(b)});const post=async(m,p,b)=>{const r=await m.POST(req(p,b));return {status:r.status,data:await r.json()}};
let r=await post(modules.library,'library',{gameId:id,status:'planned',note:'private',rating:4});assert.equal(r.status,200);
globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await (await modules.library.GET()).json()).entries.length,0);let lr=await post(modules.lists,'lists',{action:'create',name:'B list'});const bList=lr.data.id;assert.equal(lr.status,200);
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};assert.equal((await post(modules.lists,'lists',{action:'add',listId:bList,gameId:id})).status,404);const own=await post(modules.lists,'lists',{action:'create',name:'A list'});const ownId=own.data.id;assert.equal((await post(modules.lists,'lists',{action:'add',listId:ownId,gameId:id})).status,200);assert.equal((await (await modules.lists.GET()).json()).lists[0].games[0],id);
assert.equal((await modules.library.POST(req('library',{gameId:id,status:'planned',note:'',rating:null},'POST','https://evil.example'))).status,403);assert.equal((await post(modules.library,'library',{gameId:id,status:'hacked',note:'',rating:null})).status,400);
assert.equal((await post(modules.views,'views',{gameId:id})).data.count,1);assert.equal((await post(modules.views,'views',{gameId:id})).data.count,1);globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await post(modules.views,'views',{gameId:id})).data.count,2);
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};await modules.library.DELETE(req('library',{gameId:id},'DELETE'));assert.equal((await (await modules.library.GET()).json()).entries.length,0);assert.equal((await (await modules.lists.GET()).json()).lists[0].games.length,0);globalThis.testUser=null;assert.equal((await modules.library.GET()).status,401);assert.equal((await post(modules.library,'library',{gameId:id,status:'planned',note:'',rating:null})).status,401);assert.equal((await modules.lists.GET()).status,401);
const importRoute=modules['library/import'];globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};assert.equal((await post(importRoute,'library/import',{entries:[{gameId:id,status:'playing',note:'Restored private',rating:3}]})).status,200);const restored=await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]});assert.equal(restored.status,200);const restoredAgain=await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]});assert.equal(restoredAgain.data.listId,restored.data.listId);globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]})).status,400);assert.equal((await (await modules.library.GET()).json()).entries.length,0);assert.equal((await modules.catalog.POST(req('catalog',{ids:[]}))).status,400);assert.equal((await modules.catalog.POST(req('catalog',{ids:[id,id]}))).status,400);globalThis.testUser=null;assert.equal((await post(importRoute,'library/import',{entries:[]})).status,401);

const getReq=query=>new Request('https://test.example/api/catalog'+query);
let catalogResponse=await modules.catalog.GET(getReq(''));
assert.equal(catalogResponse.status,200);
const firstPage=await catalogResponse.json();
assert.equal(firstPage.apiVersion,2);assert.equal(firstPage.games.length,24);
assert.equal(firstPage.total,1323);assert.equal(firstPage.catalogStats.scores,JSON.parse(fs.readFileSync('data/METACRITIC-STEP3-REPORT.json','utf8')).scores);
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};
const privatePage=await (await modules.catalog.GET(getReq('?library=1'))).json();
assert.deepEqual(privatePage.games.map(g=>g.id),[id]);
assert(!JSON.stringify(firstPage).includes('Restored private'),'Public game payload must not include private notes');
globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};
const otherPage=await (await modules.catalog.GET(getReq('?library=1'))).json();
assert.equal(otherPage.total,0);
globalThis.testUser=null;
assert.equal((await modules.catalog.GET(getReq('?library=1'))).status,401);
assert.equal((await modules.catalog.GET(getReq('?sort=DROP%20TABLE%20library'))).status,400);
assert.equal((await modules.games.GET(new Request('https://test.example/api/games?ids='+Array.from({length:61},(_,i)=>'game-'+i).join(',')))).status,400);
const detailRecords=await (await modules.games.GET(new Request('https://test.example/api/games?ids=kenshi,minecraft'))).json();
assert.equal(detailRecords.games.length,2);assert.equal(detailRecords.games[1].catalogScope,'archive');
assert(sqlite.prepare('SELECT note FROM library WHERE user_id=? AND game_id=?').get('user-a',id).note==='Restored private');
console.log('Passed: authenticated CRUD, user isolation, list ownership, CSRF, validation, transactional dedup views, delete cascade, anonymous denial.');sqlite.close();
