import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';import {DatabaseSync} from 'node:sqlite';import {strict as assert} from 'node:assert';const esbuildPackage=fs.readdirSync('node_modules/.pnpm').find(x=>x.startsWith('esbuild@'));const {build}=await import(pathToFileURL(path.resolve('node_modules/.pnpm',esbuildPackage,'node_modules/esbuild/lib/main.js')).href);
const sqlite=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8').replaceAll('--> statement-breakpoint',''));
class Statement{constructor(sql,args=[]){this.sql=sql;this.args=args}bind(...args){return new Statement(this.sql,args)}async all(){return {results:sqlite.prepare(this.sql).all(...this.args)}}async first(){return sqlite.prepare(this.sql).get(...this.args)||null}async run(){return sqlite.prepare(this.sql).run(...this.args)}}
globalThis.testDb={prepare:sql=>new Statement(sql),batch:async stmts=>{sqlite.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}};globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};
const routeNames=['library','lists','views','library/import','catalog'];const modules={};for(const name of routeNames){const dest='/tmp/neoynasam-api-'+name.replaceAll('/','-')+'.mjs';await build({entryPoints:['app/api/'+name+'/route.ts'],outfile:dest,bundle:true,platform:'node',format:'esm',plugins:[{name:'test-env',setup(b){b.onResolve({filter:/cloudflare:workers/},()=>({path:'cloudflare',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const env={DB:globalThis.testDb};',loader:'js'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'mock-auth'}));b.onLoad({filter:/.*/,namespace:'mock-auth'},()=>({contents:'export async function getChatGPTUser(){return globalThis.testUser;}',loader:'js'}));}}]});modules[name]=await import(pathToFileURL(dest).href);}
const catalog=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));const id=catalog.find(x=>x.name==='Kenshi').id;const req=(p,b,method='POST',origin='https://test.example')=>new Request('https://test.example/api/'+p,{method,headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(b)});const post=async(m,p,b)=>{const r=await m.POST(req(p,b));return {status:r.status,data:await r.json()}};
let r=await post(modules.library,'library',{gameId:id,status:'planned',note:'private',rating:4});assert.equal(r.status,200);
globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await (await modules.library.GET()).json()).entries.length,0);let lr=await post(modules.lists,'lists',{action:'create',name:'B list'});const bList=lr.data.id;assert.equal(lr.status,200);
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};assert.equal((await post(modules.lists,'lists',{action:'add',listId:bList,gameId:id})).status,404);const own=await post(modules.lists,'lists',{action:'create',name:'A list'});const ownId=own.data.id;assert.equal((await post(modules.lists,'lists',{action:'add',listId:ownId,gameId:id})).status,200);assert.equal((await (await modules.lists.GET()).json()).lists[0].games[0],id);
assert.equal((await modules.library.POST(req('library',{gameId:id,status:'planned',note:'',rating:null},'POST','https://evil.example'))).status,403);assert.equal((await post(modules.library,'library',{gameId:id,status:'hacked',note:'',rating:null})).status,400);
assert.equal((await post(modules.views,'views',{gameId:id})).data.count,1);assert.equal((await post(modules.views,'views',{gameId:id})).data.count,1);globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await post(modules.views,'views',{gameId:id})).data.count,2);
globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};await modules.library.DELETE(req('library',{gameId:id},'DELETE'));assert.equal((await (await modules.library.GET()).json()).entries.length,0);assert.equal((await (await modules.lists.GET()).json()).lists[0].games.length,0);globalThis.testUser=null;assert.equal((await modules.library.GET()).status,401);assert.equal((await post(modules.library,'library',{gameId:id,status:'planned',note:'',rating:null})).status,401);assert.equal((await modules.lists.GET()).status,401);
const importRoute=modules['library/import'];globalThis.testUser={userId:'user-a',email:'a@example.test',displayName:'A'};assert.equal((await post(importRoute,'library/import',{entries:[{gameId:id,status:'playing',note:'Restored private',rating:3}]})).status,200);const restored=await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]});assert.equal(restored.status,200);const restoredAgain=await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]});assert.equal(restoredAgain.data.listId,restored.data.listId);globalThis.testUser={userId:'user-b',email:'b@example.test',displayName:'B'};assert.equal((await post(importRoute,'library/import',{collectionName:'Restored collection',games:[id]})).status,400);assert.equal((await (await modules.library.GET()).json()).entries.length,0);assert.equal((await modules.catalog.POST(req('catalog',{ids:[]}))).status,400);assert.equal((await modules.catalog.POST(req('catalog',{ids:[id,id]}))).status,400);globalThis.testUser=null;assert.equal((await post(importRoute,'library/import',{entries:[]})).status,401);
console.log('Passed: authenticated CRUD, user isolation, list ownership, CSRF, validation, transactional dedup views, delete cascade, anonymous denial.');sqlite.close();
