import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
const coverage=JSON.parse(fs.readFileSync('data/METACRITIC-STEP3-REPORT.json','utf8'));
const fixture=createCatalogFixture(),{database,sqlite}=fixture;
const bootstrap=await moduleFor('lib/catalog-bootstrap.ts'),ingest=await moduleFor('lib/catalog-ingest.ts');
const first=await bootstrap.ensureCatalogReady(database);assert.equal(first.ready,false);assert.equal(first.processed,20);assert(fixture.queries.length<=48,'Bootstrap chunk exceeds invocation query allowance');
await readyCatalog(bootstrap);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM catalog_games WHERE status='published'").get().n,1323);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM catalog_games WHERE status='archived'").get().n,3);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM catalog_scores').get().n,coverage.scores);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM catalog_scores WHERE platform IS NULL AND edition_id IS NULL').get().n,coverage.platformUnknown);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM catalog_scores WHERE platform=?').get('PC').n,coverage.verifiedPcScores);assert(fixture.queries.every(q=>q.args.length<=100));
const {metacriticScoreForGame}=await import('../lib/metacritic-identity.mjs');const originalGames=JSON.parse(fs.readFileSync('data/catalog.json','utf8')),originalScores=JSON.parse(fs.readFileSync('data/metacritic-users.json','utf8')),originalIdentities=JSON.parse(fs.readFileSync('data/game-identities.json','utf8'));for(const original of originalGames){const projected=JSON.parse(sqlite.prepare('SELECT payload FROM catalog_games WHERE id=?').get(original.id).payload);assert.deepEqual(projected.metacriticUser,metacriticScoreForGame(original,originalIdentities,originalScores),'Saved score record changed: '+original.id);}
const shell=sqlite.prepare("SELECT score_count FROM catalog_games WHERE name='Mortal Shell II'").get();assert.equal(shell.score_count,507);assert(sqlite.prepare('SELECT COUNT(*) n FROM catalog_games WHERE score_value IS NOT NULL AND score_count IS NULL').get().n>0);
const game={id:'catalog-fixture-game',name:'İğne Işığı',steamAppId:99000001,platforms:['PC'],genres:['Aksiyon'],pcSystems:['Windows'],year:null,desc:'kaynak açıklaması',steamTags:{steamAppId:99000001,identityTitle:'İğne Işığı',tags:[{id:99001,name:'Synthetic',count:25}]},sourceUrl:'https://example.test/game',sourceRetrievedAt:'2026-10-07'};
await ingest.ingestGames(database,[game],{writeLegacy:true});const original=sqlite.prepare('SELECT revision FROM catalog_games WHERE id=?').get(game.id).revision;await ingest.ingestGames(database,[game],{writeLegacy:true});assert.equal(sqlite.prepare('SELECT revision FROM catalog_games WHERE id=?').get(game.id).revision,original);assert.equal(sqlite.prepare('SELECT game_count FROM catalog_tags WHERE id=99001').get().game_count,1);assert(sqlite.prepare('SELECT id FROM source_games WHERE id=?').get(game.id));
const fresh=JSON.parse(sqlite.prepare('SELECT payload FROM catalog_games WHERE id=?').get(game.id).payload);assert.equal(fresh.mood,'challenge');assert.equal(fresh.desc,'kaynak açıklaması');assert.equal(fresh.long,'kaynak açıklaması');
sqlite.prepare('INSERT INTO catalog_overrides(game_id,field,value,updated_at) VALUES(?,?,?,?)').run(game.id,'desc',JSON.stringify('Samet açıklaması'),'2026-10-07');await ingest.updateProjection(database,{...game,desc:'yeni kaynak açıklaması'},{writeLegacy:true});let projected=sqlite.prepare('SELECT payload,base_payload FROM catalog_games WHERE id=?').get(game.id);assert.equal(JSON.parse(projected.payload).desc,'Samet açıklaması');assert.equal(JSON.parse(projected.base_payload).desc,'yeni kaynak açıklaması');sqlite.prepare('DELETE FROM catalog_overrides WHERE game_id=?').run(game.id);await ingest.updateProjection(database,{...game,desc:'yeni kaynak açıklaması',steamTags:{tags:[]}});projected=sqlite.prepare('SELECT payload FROM catalog_games WHERE id=?').get(game.id);assert.equal(JSON.parse(projected.payload).desc,'yeni kaynak açıklaması');assert.equal(sqlite.prepare('SELECT game_count FROM catalog_tags WHERE id=99001').get().game_count,0);
await assert.rejects(ingest.ingestGames(database,[{...game,id:'wrong-edition'}]),/kimliği/);await assert.rejects(ingest.ingestGames(database,[{...game,steamAppId:99000002}]),/sürüm/);assert(!sqlite.prepare('SELECT id FROM catalog_games WHERE id=?').get('wrong-edition'));assert(sqlite.prepare('SELECT token FROM catalog_search_terms WHERE token=? AND game_id=?').get('igne',game.id));
await ingest.ingestGames(database,[{...game,id:'wrong-tag-game',steamAppId:99000003,steamTags:{steamAppId:99000003,identityTitle:'another title',tags:[{id:99002,name:'Wrong tag',count:20}]}}]);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM catalog_game_tags WHERE game_id=?').get('wrong-tag-game').n,0);
// A stale bootstrap worker cannot overwrite a newer projection or its relations.
await ingest.ingestGames(database,[{...game,name:'stale worker'}],{priority:10,gate:{id:bootstrap.CATALOG_BOOTSTRAP_ID,stage:'seed',cursor:'0',token:'expired-token'}});assert.equal(sqlite.prepare('SELECT name FROM catalog_games WHERE id=?').get(game.id).name,'İğne Işığı');
// A transaction failure never moves the bootstrap cursor and can be retried.
const broken=createCatalogFixture(),goodBatch=broken.database.batch;broken.database.batch=async statements=>goodBatch([...statements,broken.database.prepare('INSERT INTO missing_table VALUES(1)')]);await assert.rejects(bootstrap.ensureCatalogReady(broken.database));assert.equal(broken.sqlite.prepare('SELECT COUNT(*) n FROM catalog_games').get().n,0);assert.equal(broken.sqlite.prepare('SELECT cursor,lease_token FROM catalog_bootstrap').get().cursor,'0');assert.equal(broken.sqlite.prepare('SELECT lease_token FROM catalog_bootstrap').get().lease_token,null);broken.database.batch=goodBatch;const [one,two]=await Promise.all([bootstrap.ensureCatalogReady(broken.database),bootstrap.ensureCatalogReady(broken.database)]);assert.equal(Math.max(one.processed,two.processed),20);assert([one,two].every(r=>r.processed>=0&&r.processed<=20));assert.equal(broken.sqlite.prepare('SELECT COUNT(*) n FROM catalog_games').get().n,20);broken.close();
// Exact source IDs survive a seed-to-legacy migration, without replacing personal records.
const legacy=createCatalogFixture();legacy.sqlite.prepare('INSERT INTO source_games(id,qid,payload,fetched_at) VALUES(?,?,?,?)').run(game.id,'steam:'+game.steamAppId,JSON.stringify(game),'2026-10-07');legacy.sqlite.prepare('INSERT INTO library(user_id,game_id,status,note,updated_at) VALUES(?,?,?,?,?)').run('user-fixture',game.id,'playing','özel not','2026-10-07');await readyCatalog(bootstrap);assert.equal(legacy.sqlite.prepare('SELECT COUNT(*) n FROM catalog_games').get().n,1327);assert.equal(legacy.sqlite.prepare('SELECT note FROM library').get().note,'özel not');assert.equal(legacy.sqlite.prepare('SELECT source_priority FROM catalog_games WHERE id=?').get(game.id).source_priority,20);legacy.close();
// Offline full database backup, dry run and restore preserve all tables and user data.
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'neoynasam-backup-')),dbPath=path.join(dir,'catalog.sqlite'),backupPath=path.join(dir,'backup.sqlite');const disk=createCatalogFixture(dbPath);disk.sqlite.prepare('INSERT INTO library(user_id,game_id,status,note,updated_at) VALUES(?,?,?,?,?)').run('private-user',game.id,'playing','saklanan not','2026-10-07');disk.sqlite.prepare('INSERT INTO lists(id,user_id,name,created_at) VALUES(?,?,?,?)').run('private-list','private-user','Özel liste','2026-10-07');disk.sqlite.prepare('INSERT INTO list_games(list_id,game_id) VALUES(?,?)').run('private-list',game.id);disk.close();const run=(file,args)=>{const result=spawnSync(process.execPath,[file,...args],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout);};const partial=run('scripts/catalog-backfill.mjs',['--database',dbPath,'--max-chunks','2']);assert.equal(partial.cursor,'40');assert(partial.rollbackBackup);const resumed=run('scripts/catalog-backfill.mjs',['--database',dbPath,'--max-chunks','2']);assert.equal(resumed.cursor,'80');const saved=run('scripts/catalog-backup.mjs',['--database',dbPath,'--output',backupPath]);assert.equal(saved.tables.library,1);const modified=new DatabaseSync(dbPath);modified.exec('DELETE FROM library');modified.close();const dry=run('scripts/catalog-restore.mjs',['--database',dbPath,'--backup',backupPath,'--dry-run']);assert.equal(dry.dryRun,true);const before=new DatabaseSync(dbPath);assert.equal(before.prepare('SELECT COUNT(*) n FROM library').get().n,0);before.close();const restored=run('scripts/catalog-restore.mjs',['--database',dbPath,'--backup',backupPath,'--apply']);assert(restored.rollbackBackup);const after=new DatabaseSync(dbPath);assert.equal(after.prepare('SELECT note FROM library').get().note,'saklanan not');assert.equal(after.prepare('SELECT COUNT(*) n FROM list_games').get().n,1);after.close();fs.rmSync(dir,{recursive:true});fixture.close();
console.log('Passed: resumable atomic catalog migration, 1323+3 stable IDs, accepted scores and507 verified count, identity conflicts, nullable provenance, manual overrides/rawbase, idempotency, stale leases, tag counts, oldcode mirror, full SQLite backup/dry-run/restore.');
