const fs=require('node:fs'),vm=require('node:vm');
function createHarness({html=fs.readFileSync('public/index.html','utf8'),pathname='/',search='',user={name:'Samet',email:'samet@example.test'},initialRecords=[],initialLists=[],storage={},requestHook}={}){
 const elements={},classes=new Set(),listeners={},stored=storage;
 let records=initialRecords.map(x=>({...x})),lists=initialLists.map(x=>({...x,games:[...x.games]}));
 const requests=[],navigation=[],source=JSON.parse(fs.readFileSync('data/catalog.json','utf8'));
 const scoreData=JSON.parse(fs.readFileSync('data/metacritic-users.json','utf8')),scoreIdentities=JSON.parse(fs.readFileSync('data/game-identities.json','utf8'));
 const reviewData=new Map(JSON.parse(fs.readFileSync('data/steam-all-reviews.json','utf8')).changes.map(c=>[c.gameId,c]));
 const tagData=JSON.parse(fs.readFileSync('data/steam-tags.json','utf8')),tagLabels=JSON.parse(fs.readFileSync('data/steam-tag-labels.json','utf8'));
 const archived=JSON.parse(fs.readFileSync('data/legacy-catalog.json','utf8')),editorial=JSON.parse(fs.readFileSync('public/editorial.json','utf8'));
 const normalized=s=>String(s||'').toLocaleLowerCase('tr').replaceAll('ı','i').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 const byApp=new Map(Object.values(editorial).filter(e=>e.steamAppId).map(e=>[e.steamAppId,e]));
 function fixtureGame(raw){const ed=editorial[raw.name]||byApp.get(raw.steamAppId)||{},genres=raw.genres.join(' ');const mood=ed.mood||(/Strateji|Bulmaca/.test(genres)?'think':/Simülasyon|Yarış|Spor/.test(genres)?'relax':/Platform|Roguelike|Korku|Nişancı/.test(genres)?'challenge':/Açık dünya|Hayatta kalma/.test(genres)?'world':/RPG|Macera/.test(genres)?'story':'challenge');const desc=ed.desc||raw.discoveryHook||raw.publisherDescription||'Tanıtım bekleniyor';const observation=reviewData.get(raw.id);return {...raw,...(observation&&observation.steamAppId===raw.steamAppId?{steamReview:observation.review}:{}),steamTags:tagData[String(raw.steamAppId)]||null,metacriticUser:scoreData[scoreIdentities[raw.id]?.scoreRecordId]||null,mood,kind:ed.kind||'city',colors:ed.colors||['#244451','#102b35','#88c8c8'],desc,long:ed.long||raw.discoveryBody||desc,editorial:!!ed.desc,viewCount:0};}
 const games=source.map(fixtureGame),archives=archived.map(g=>fixtureGame({...g,catalogScope:'archive'})),allGames=[...games,...archives],gameMap=new Map(allGames.map(g=>[g.id,g]));
 const catalogStats={games:games.length,covers:games.filter(g=>g.coverUrl).length,scores:games.filter(g=>g.metacriticUser&&g.metacriticUser.metric==='user-score').length};
 const genres=[...new Set(games.flatMap(g=>g.genres))].sort((a,b)=>a.localeCompare(b,'tr')),moodCounts={};for(const g of games)moodCounts[g.mood]=(moodCounts[g.mood]||0)+1;
 function elem(id){let inner='',value='';const e={id,hidden:false,textContent:'',disabled:false,open:false,files:[],options:[],classList:{add(){},remove(){},toggle(){},contains(){return false}},addEventListener(type,fn){this['on'+type]=fn},scrollIntoView(){this.scrollCalls=(this.scrollCalls||0)+1},focus(){},showModal(){this.open=true},close(){this.open=false;this.onclose?.()},setAttribute(k,v){this[k]=v},removeAttribute(k){delete this[k]},contains(){return false},pause(){this.paused=true},load(){},play(){this.playing=true;return Promise.resolve()},canPlayType(){return ''},querySelectorAll(){return []},querySelector(){return {disabled:false,scrollIntoView(){}}},getBoundingClientRect(){return {left:0,right:100,top:0,bottom:100}}};Object.defineProperty(e,'innerHTML',{get:()=>inner,set:v=>{inner=v;const opts=[...v.matchAll(/<option(?: value="([^"]*)")?[^>]*>([^<]*)<\/option>/g)];if(opts.length||e.isSelect){e.options=opts.map(m=>({value:m[1]===undefined?m[2]:m[1],textContent:m[2]}));if(e.isSelect)value=e.options[0]?.value||'';}for(const match of v.matchAll(/\bid="([^"]+)"/g))elements[match[1]]??=elem(match[1]);}});Object.defineProperty(e,'value',{get:()=>value,set:v=>{value=e.isSelect&&!e.options.some(o=>o.value===String(v))?'':String(v);}});Object.defineProperty(e,'selectedIndex',{get:()=>e.options.findIndex(o=>o.value===value)});Object.defineProperty(e,'selectedOptions',{get:()=>e.options.filter(o=>o.value===value)});return e;}
 for(const m of html.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g)){const e=elements[m[1]]=elem(m[1]);e.isSelect=/^<select\b/.test(m[0]);e.hidden=/\bhidden(?:[\s=>]|$)/.test(m[0]);e.outerHTML=m[0];}
 for(const id of Object.values(elements).filter(e=>e.isSelect).map(e=>e.id)){const chunk=html.match(new RegExp('<select id="'+id+'"[^>]*>([\\s\\S]*?)</select>'));if(chunk)elements[id].innerHTML=chunk[1];}elements.sort.value='editor';
 function within(p,value,min,max){const lo=p.get(min),hi=p.get(max);return !lo&&!hi||Number.isFinite(value)&&(!lo||value>=Number(lo))&&(!hi||value<=Number(hi));}
 function catalogResponse(p){let filtered=p.get('library')==='1'?(user?allGames.filter(g=>records.some(e=>e.gameId===g.id)):[]):games;const queryWords=normalized(p.get('q')).split(/[^\p{L}\p{N}]+/u).filter(Boolean);filtered=filtered.filter(g=>{const entry=records.find(e=>e.gameId===g.id),list=lists.find(l=>l.id===p.get('collection'));return queryWords.every(q=>normalized(g.name+' '+g.desc+' '+g.genres.join(' ')+' '+(g.studio||'')).split(/[^\p{L}\p{N}]+/u).some(word=>word.startsWith(q)))&&(!p.get('genre')||g.genres.includes(p.get('genre')))&&(!p.get('mood')||g.mood===p.get('mood'))&&(!p.get('system')||g.pcSystems?.includes(p.get('system')))&&within(p,g.metacriticUser?.score,'rating','ratingMax')&&within(p,g.steamReview?.positivePercent,'steamMin','steamMax')&&within(p,g.metacriticUser?.userRatings,'mcCountMin','mcCountMax')&&within(p,g.steamReview?.total,'steamCountMin','steamCountMax')&&(!p.get('features')||(p.get('features')==='turkish'?g.hasTurkish===true:g.hasCoop===true))&&(!p.get('status')||entry?.status===p.get('status'))&&(!p.get('collection')||list?.games.includes(g.id))&&(!p.get('era')||(g.year&&(p.get('era')==='2020'?g.year>=2020:p.get('era')==='2010'?g.year>=2010&&g.year<=2019:g.year<=2009)));});const sort=p.get('sort');if(sort==='name')filtered=[...filtered].sort((a,b)=>a.name.localeCompare(b.name,'tr'));if(sort==='new')filtered=[...filtered].sort((a,b)=>(b.year||0)-(a.year||0));if(sort==='old')filtered=[...filtered].sort((a,b)=>(a.year||9999)-(b.year||9999));if(sort==='rating')filtered=[...filtered].sort((a,b)=>(b.metacriticUser?.score??-1)-(a.metacriticUser?.score??-1));if(sort==='steam')filtered=[...filtered].sort((a,b)=>(b.steamReview?.positivePercent??-1)-(a.steamReview?.positivePercent??-1));const pageSize=Number(p.get('pageSize')||24),pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)),page=Math.min(pageCount,Math.max(1,Number(p.get('page')||1))),offset=p.get('random')==='1'?Math.max(0,filtered.length-1):(page-1)*pageSize;return {apiVersion:2,games:filtered.slice(offset,offset+pageSize),total:filtered.length,page,pageSize,pageCount,catalogStats,genres,steamTagLabels:tagLabels,moodCounts,fetchedAt:null};}
 const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
 const fetch=async(path,options={})=>{const method=options.method||'GET',body=options.body?JSON.parse(options.body):null;requests.push({path,method,body,signal:options.signal});if(options.signal?.aborted){const error=new Error('Aborted');error.name='AbortError';throw error;}const url=new URL(path,'https://test.example');let data;
  if(url.pathname==='/api/catalog')data=method==='POST'?{games:(body.ids||[]).map(id=>gameMap.get(id)).filter(Boolean),fetchedAt:new Date().toISOString(),updated:body.ids.length,failed:[]}:catalogResponse(url.searchParams);
  else if(url.pathname==='/api/games'){const ids=(url.searchParams.get('ids')||'').split(','),apps=(url.searchParams.get('steamAppIds')||'').split(',').map(Number);data={games:allGames.filter(g=>ids.includes(g.id)||apps.includes(g.steamAppId)).slice(0,60)};}
  else if(url.pathname==='/api/spotlight')data={date:'2026-10-06',nextRefreshAt:new Date(Date.now()+86400000).toISOString(),games:games.filter(g=>[233860,312520,653530,1055540,365360].includes(g.steamAppId)).map(g=>({gameId:g.id,kicker:'KEŞİF',reason:'Öneri',game:g}))};
  else if(url.pathname==='/api/related'){const g=gameMap.get(url.searchParams.get('gameId')),native=g?.id==='kenshi'?[1857950,1203620,1129580]:[],tagIds=new Set(g?.steamTags?.tags.map(t=>t.id)||[]);const candidates=[...native.map(id=>games.find(x=>x.steamAppId===id)).filter(Boolean),...games.filter(x=>x.id!==g?.id&&x.steamTags?.tags.filter(t=>tagIds.has(t.id)).length>=2)];const seen=new Set();data={recommendations:candidates.filter(x=>!seen.has(x.id)&&seen.add(x.id)).slice(0,20).map(game=>({game,score:0.5,origin:native.includes(game.steamAppId)?'steam':'tags',shared:game.steamTags?.tags.filter(t=>tagIds.has(t.id))||[]}))};}
  else if(url.pathname==='/api/media'){const g=gameMap.get(url.searchParams.get('gameId'));data={steamAppId:g?.steamAppId||233860,name:g?.name||'Kenshi',sourceUrl:'https://store.steampowered.com/app/233860/',items:[{kind:'video',format:'hls',name:'Kenshi trailer',src:'https://video.akamai.steamstatic.com/store_trailers/233860/test/hls.m3u8',thumbnail:'https://shared.akamai.steamstatic.com/steam/apps/123/movie.jpg'},{kind:'image',format:'image',name:'Screenshot',src:'https://shared.akamai.steamstatic.com/steam/apps/233860/ss.jpg',thumbnail:'https://shared.akamai.steamstatic.com/steam/apps/233860/ss.jpg'}]};}
  else if(url.pathname==='/api/me')data={user,signin:'/signin-with-chatgpt?return_to=%2Fkoleksiyonum',signout:'/signout-with-chatgpt'};
  else if(url.pathname==='/api/views'&&method==='POST')data={count:1};
  else if(url.pathname==='/api/library'){if(method==='POST'){records=records.filter(e=>e.gameId!==body.gameId);records.push(body);data={entry:body};}else if(method==='DELETE'){records=records.filter(e=>e.gameId!==body.gameId);data={ok:true};}else data={entries:records};}
  else if(url.pathname==='/api/library/import'){for(const row of body.entries||[]){records=records.filter(e=>e.gameId!==row.gameId);records.push(row);}data={ok:true};}
  else if(url.pathname==='/api/lists')data={lists};
  else throw new Error('Unexpected request '+path);
  const hooked=await requestHook?.({path,url,options,body,data,requests,response});return hooked===undefined?response(data):hooked;
 };
 const loc={href:'https://test.example'+pathname+search,search,pathname,assign:path=>navigation.push(path),replace:path=>navigation.push(path)};
 const ctx={document:{getElementById:id=>elements[id]||null,addEventListener:(t,fn)=>{const old=listeners[t];listeners[t]=old?e=>{old(e);return fn(e)}:fn},querySelectorAll:q=>q==='dialog'?Object.values(elements).filter(e=>/Dialog|detail|quiz/.test(e.id)):[],body:{dataset:{page:html.match(/<body[^>]*data-page="([^"]+)"/)?.[1]||'discover'},classList:{add:x=>classes.add(x),toggle:x=>classes.has(x)?classes.delete(x):classes.add(x),contains:x=>classes.has(x)}}},fetch,AbortController,localStorage:{getItem:k=>stored[k]||null,setItem:(k,v)=>stored[k]=v,removeItem:k=>delete stored[k]},URL,URLSearchParams,Blob,location:loc,history:{replaceState(a,b,path){loc.href='https://test.example'+path;loc.search=new URL(loc.href).search;loc.pathname=new URL(loc.href).pathname}},setTimeout:(f,d)=>{const t=setTimeout(f,d);if(d>100)t.unref();return t},clearTimeout,requestAnimationFrame:f=>f(),console,navigator:{clipboard:{writeText:async()=>{}}},confirm:()=>true};
 vm.createContext(ctx);for(const file of ['ui','discovery','media','related'])vm.runInContext(fs.readFileSync('public/'+file+'.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/app.js','utf8'),ctx);
 return {ctx,elements,classes,listeners,storage:stored,source,scoreData,scoreIdentities,archived,requests,navigation,location:loc,games,allGames,get records(){return records},get lists(){return lists}};
}
module.exports={createHarness};
