const vm=require('node:vm'),assert=require('node:assert/strict');
const {createHarness}=require('./frontend-harness.cjs');const sleep=ms=>new Promise(r=>setTimeout(r,ms)),run=(h,c)=>vm.runInContext(c,h.ctx),stop=h=>run(h,'closeMedia();stopSpotlight();clearTimeout(spotlightRefreshTimer)');
(async()=>{
 const h=createHarness({search:'?genre=Aksiyon&genre=Korku&tag=19&play=single&steamMin=50&system=Windows'});await sleep(80);
 const p=new URL(h.location.href).searchParams;assert.deepEqual(p.getAll('genre'),['Aksiyon','Korku']);assert.deepEqual(p.getAll('tag'),['19']);assert.deepEqual(p.getAll('play'),['single']);assert.equal(p.get('steamMin'),'50');assert.equal(p.get('system'),'Windows');
 assert(run(h,'state.games.every(g=>g.genres.includes("Aksiyon")&&g.genres.includes("Korku")&&g.steamTags.tags.some(t=>t.id===19)&&g.gameplay.features.single===true&&g.steamReview.positivePercent>=50)'));
 assert(h.elements.activeFilters.innerHTML.includes('data-clear-multi="genres"'));assert(h.elements.activeFilters.innerHTML.includes('data-clear-multi="tags"'));assert(h.elements.activeFilters.innerHTML.includes('data-clear-multi="gameplay"'));
 const existing=h.requests.length;h.elements.tagFilterSearch.value='souls';h.listeners.input({target:h.elements.tagFilterSearch});assert.equal(h.requests.length,existing,'Searching filter options does not query the game catalog');assert(run(h,'multiFilterOptions("tags","souls").every(o=>norm(o.search).includes("souls"))'));
 h.elements.tagFilterSearch.value='';run(h,'state.page=2');await h.listeners.change({target:{dataset:{multi:'gameplay'},value:'coop-online',checked:true}});await sleep(40);assert.equal(run(h,'state.page'),1);assert(run(h,'multiSelection.genres.has("Korku")&&multiSelection.tags.has("19")&&multiSelection.gameplay.has("single")'));assert(new URL(h.location.href).searchParams.getAll('play').includes('coop-online'));
 const chip={dataset:{clearMulti:'gameplay',value:'coop-online'}};h.listeners.click({target:{closest:s=>s==='[data-clear-multi]'?chip:null}});await sleep(40);assert(!run(h,'multiSelection.gameplay.has("coop-online")'));assert(run(h,'multiSelection.gameplay.has("single")&&multiSelection.genres.size===2'));assert.equal(h.elements.steamMin.value,'50');
 run(h,'multiSelection.tags.add("999999999");renderMultiFilters()');await run(h,'submitSearch()');assert.equal(run(h,'state.total'),0);assert(run(h,'multiSelection.tags.has("999999999")'),'Zero results never relax selected conditions');assert(h.location.search.includes('999999999'));await run(h,'clear()');await sleep(40);assert(run(h,'Object.values(multiSelection).every(s=>s.size===0)'));assert.equal(run(h,'state.total'),1323);
 const game=h.allGames.find(g=>g.gameplay?.features['remote-play-together']);h.ctx.sample=game;assert(run(h,'gameplayDetails(sample).includes("doğal online co-op desteği değildir")'));assert((run(h,'gameplayBadges(sample)').match(/<span>/g)||[]).length<=2);assert(run(h,'gameplayValue({steamAppId:1},"single")')==='Belirtilmemiş');
 await run(h,'openGame(sample.id)');assert(h.elements.detailContent.innerHTML.includes('Oynanış'));assert(h.elements.detailContent.innerHTML.includes('Detaylı etiketler'));stop(h);
 const old=createHarness({search:'?features=coop'});await sleep(60);assert(run(old,'multiSelection.gameplay.has("coop")'));assert.equal(old.elements.features.value,'');assert(old.location.search.includes('play=coop'));assert(!old.location.search.includes('features=coop'));stop(old);
 console.log('Passed: multi-filter AND/URL restoration, independent source score ranges, option search without requests, removable chips, page reset, exact zero results, complete reset, bounded card badges/detail labels and legacy co-op links.');
})().catch(e=>{console.error(e);process.exitCode=1});
