import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import harness from './frontend-harness.cjs';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
const fixture=createCatalogFixture();
const bootstrap=await moduleFor('lib/catalog-bootstrap.ts');await readyCatalog(bootstrap);
const repository=await moduleFor('lib/catalog-repository.ts');
const run=(h,code)=>vm.runInContext(code,h.ctx),pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const stop=h=>run(h,'closeMedia();stopSpotlight();clearTimeout(spotlightRefreshTimer)');
const catalogHook=async({url,response,data})=>{
 if(url.pathname==='/api/catalog')return response(await repository.queryCatalog(repository.parseCatalogQuery(url.searchParams),'integration-user'));
 if(url.pathname==='/api/games')return response({apiVersion:2,games:await repository.gamesByIds((url.searchParams.get('ids')||'').split(',').filter(Boolean))});
 return response(data);
};
const seed=JSON.parse(fs.readFileSync('data/catalog.json','utf8')),ed=JSON.parse(fs.readFileSync('public/editorial.json','utf8'));
const h=harness.createHarness({user:null,search:'?q=kens',requestHook:catalogHook});
// Wait for the actual SQL response; fixed sleeps fail under concurrent test load.
for(let attempt=0;attempt<200&&!run(h,'state.loaded');attempt++)await pause(10);
assert.equal(run(h,'state.loaded'),true);assert.equal(run(h,'state.catalogStats.games'),1323);assert.equal(run(h,'state.catalogStats.scores'),JSON.parse(fs.readFileSync('data/METACRITIC-STEP3-REPORT.json','utf8')).scores);
assert(run(h,'state.games.some(g=>g.id==="kenshi")'),'The browser uses real SQL prefix results');
assert.equal(run(h,'nameGame("kenshi").desc'),ed.Kenshi.desc,'Server enrichment preserves authored discovery hooks');
assert.equal(run(h,'nameGame("kenshi").long'),ed.Kenshi.long);
await run(h,'clear()');assert.equal(run(h,'state.games.length'),24);assert.equal(run(h,'state.total'),1323);
await run(h,'state.page=2;loadPage()');assert.deepEqual(Array.from(run(h,'state.games.map(g=>g.id)')),seed.slice(24,48).map(g=>g.id));
// Exercise the actual UI against SQL, rather than filtering a mock first page.
h.elements.rating.value='7';h.elements.ratingMax.value='8,5';h.elements.steamMin.value='13';h.elements.steamMax.value='78';
await h.elements.ratingMax.onchange();
assert(run(h,'state.total')>0);assert(run(h,'state.games.every(g=>g.metacriticUser.score>=7&&g.metacriticUser.score<=8.5&&g.steamReview.positivePercent>=13&&g.steamReview.positivePercent<=78)'));
assert(new URL(h.location.href).searchParams.get('ratingMax')==='8.5');
assert(h.elements.activeFilters.innerHTML.includes('Steam 13–78 %'));
const before=run(h,'state.total'),htmlBefore=h.elements.grid.innerHTML,requestsBefore=h.requests.length;
h.elements.steamMin.value='90';await h.elements.steamMin.onchange();
assert.equal(run(h,'state.total'),before);assert.equal(h.elements.grid.innerHTML,htmlBefore);assert.equal(h.requests.length,requestsBefore);
assert.equal(h.elements.scoreFilterError.hidden,false);assert(h.elements.scoreFilterError.textContent.includes('en az değeri en fazla değerinden büyük olamaz'));assert.equal(h.elements.steamMin['aria-invalid'],'true');
h.elements.steamMin.value='13';await h.elements.steamMin.onchange();assert.equal(h.elements.scoreFilterError.hidden,true);
await h.elements.resetScoreFilters.onclick();
h.elements.steamCountMin.value='100000';h.elements.steamCountMax.value='500000';await h.elements.steamCountMax.onchange();
assert(run(h,'state.total')>0);assert(run(h,'state.games.every(g=>g.steamReview.total>=100000&&g.steamReview.total<=500000)'));
assert(h.elements.activeFilters.innerHTML.includes('Steam değerlendirme 100.000–500.000'),'Count range keeps an explicit removable active chip');
const shared=harness.createHarness({user:null,search:h.location.search,requestHook:catalogHook});
for(let attempt=0;attempt<200&&!run(shared,'state.loaded');attempt++)await pause(10);
assert.equal(shared.elements.steamCountMin.value,'100000');assert.equal(shared.elements.steamCountMax.value,'500000');assert.equal(run(shared,'state.total'),run(h,'state.total'));stop(shared);
await h.listeners.click({target:{closest(selector){return selector==='[data-clear-range]'?{dataset:{clearRange:'steamCountMin,steamCountMax'}}:null;}}});
assert.equal(run(h,'state.total'),1323);assert.equal(h.elements.steamCountMin.value,'');assert.equal(h.elements.steamCountMax.value,'');
h.elements.mcCountMin.value='0';await h.elements.mcCountMin.onchange();assert(run(h,'state.games.every(g=>Number.isSafeInteger(g.metacriticUser.userRatings))'));
assert(new URL(h.location.href).searchParams.get('mcCountMin')==='0','Zero is included in URL/API');
await run(h,'clear()');
h.elements.rating.value='8';h.elements.system.value='Windows';await run(h,'state.page=1;loadPage()');assert(run(h,'state.games.every(g=>userScore(g).score>=8&&g.pcSystems.includes("Windows"))'));
const helldivers=seed.find(g=>g.steamAppId===553850),mortal=seed.find(g=>g.steamAppId===2584270);
await run(h,`openGame(${JSON.stringify(helldivers.id)})`);assert(h.elements.detailContent.innerHTML.includes('7,5'));
assert.equal(run(h,'state.current.metacriticUser.platform'),null,'Historical platform-unknown scores remain visible');
for(const [app,score,platform,count] of [[3393110,6.5,'PC',13],[2215200,8.4,'PlayStation 5',635],[2357570,2,'PC',5129],[3940610,6.2,'PlayStation 5',19]]){
 const g=seed.find(g=>g.steamAppId===app);await run(h,`openGame(${JSON.stringify(g.id)})`);
 assert.equal(run(h,'state.current.metacriticUser.score'),score);assert.equal(run(h,'state.current.metacriticUser.platform'),platform);assert.equal(run(h,'state.current.metacriticUser.userRatings'),count);
 assert(h.elements.detailContent.innerHTML.includes(platform));
}
assert(h.elements.detailContent.innerHTML.includes('Kaynak önbellekleri farklı; güncellik belirsiz'));
await run(h,`state.compare=new Set(${JSON.stringify([helldivers.id,mortal.id])});showCompare()`);assert(h.elements.compareContent.innerHTML.includes('7,5/10'));assert(h.elements.compareContent.innerHTML.includes('7,8/10'));
const cs2=seed.find(g=>g.steamAppId===730);
await run(h,`openGame(${JSON.stringify(cs2.id)})`);assert(h.elements.detailContent.innerHTML.includes('5,5'));assert.equal(run(h,'state.current.metacriticUser.platform'),'PC');assert.equal(run(h,'state.current.metacriticUser.metacriticId'),'counter-strike-2');
await run(h,`state.compare=new Set(${JSON.stringify([cs2.id,mortal.id])});showCompare()`);assert(h.elements.compareContent.innerHTML.includes('5,5/10'));assert(h.elements.compareContent.innerHTML.includes('7,8/10'));
assert(!h.requests.some(r=>r.path==='/api/catalog'||r.path.startsWith('/editorial.json')||(r.path==='/api/views'&&r.method==='GET')));
assert(h.elements.compareContent.innerHTML.includes('Tüm diller · Ülke filtresi yok'));
assert(!h.elements.compareContent.innerHTML.includes('İngilizce yorumlar'));
const zero=run(h,`sourceScore({steamAppId:730,steamReview:{positivePercent:null,total:0,scope:'all-languages'}},'steam')`);assert(zero.includes('0 değerlendirme'));assert(zero.includes('Tüm diller'));assert(!zero.includes('0%'));
stop(h);fixture.close();
console.log('Passed: frontend consumes real migrated SQL catalog, prefix search, authored descriptions, stable pages, server score/system filters, and retained platform-unknown scores in detail and off-page comparison.');
