import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
import {parseSteamGameplay,validGameplay,gameplayKeys,preserveGameplay} from '../lib/steam-gameplay.mjs';
const profile=(cats,stamp='2026-10-09T00:00:00Z')=>parseSteamGameplay({steam_appid:620,type:'game',name:'Portal 2',categories:cats},620,stamp);
const generic=profile([{id:9,description:'Co-op'}]);assert.equal(generic.features.coop,true);assert.equal(generic.features['coop-online'],null);
const lan=profile([{id:48,description:'LAN Co-op'},{id:44,description:'Remote Play Together'}]);assert.equal(lan.features.coop,true);assert.equal(lan.features['coop-local'],null);assert.equal(lan.features['coop-online'],null);assert.equal(lan.crossPlayPlatforms,null);
assert(!validGameplay({...lan,steamAppId:730},620));assert(!validGameplay({...lan,features:{...lan.features,'coop-online':true}}));assert.throws(()=>parseSteamGameplay({steam_appid:730,type:'game',name:'Other',categories:[{id:9,description:'Co-op'}]},620));
assert.deepEqual(gameplayKeys({steamAppId:620,gameplay:lan}),['coop','coop-lan','remote-play-together']);
const newer=profile([{id:2,description:'Single-player'}],'2026-10-10T00:00:00Z');assert.deepEqual(preserveGameplay({gameplay:newer},{gameplay:generic},620).gameplay,newer);assert.deepEqual(preserveGameplay({gameplay:generic},{gameplay:newer},620).gameplayHistory,[generic]);assert.deepEqual(preserveGameplay({gameplay:newer},{gameplay:null},620).gameplay,newer);
const data=JSON.parse(fs.readFileSync('data/steam-gameplay.json'));const ids=new Set();for(const c of data.changes){assert(validGameplay(c.gameplay,c.steamAppId));assert(!ids.has(c.gameId));ids.add(c.gameId);}
const f=createCatalogFixture(),{sqlite,database}=f;await readyCatalog(await moduleFor('lib/catalog-bootstrap.ts'));
sqlite.exec("DELETE FROM catalog_bootstrap WHERE id LIKE 'gameplay-%'; DELETE FROM catalog_game_features");
for(const c of data.changes){const saved=sqlite.prepare('SELECT payload,base_payload FROM catalog_games WHERE id=?').get(c.gameId),base=JSON.parse(saved.base_payload),game=JSON.parse(saved.payload);delete base.gameplay;delete base.gameplayHistory;delete game.gameplay;delete game.gameplayHistory;sqlite.prepare('UPDATE catalog_games SET payload=?,base_payload=?,content_hash=? WHERE id=?').run(JSON.stringify(game),JSON.stringify(base),'before-'+c.gameId,c.gameId);sqlite.prepare('INSERT INTO source_games(id,qid,payload,fetched_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(c.gameId,'steam:'+c.steamAppId,JSON.stringify(game),'2026-10-09');}
const first=data.changes[0],manual=data.changes[1],old={...first.gameplay,retrievedAt:'2026-10-08T00:00:00Z'};
for(const [c,p] of [[first,old],[manual,manual.gameplay]]){const row=sqlite.prepare('SELECT payload,base_payload FROM catalog_games WHERE id=?').get(c.gameId);sqlite.prepare('UPDATE catalog_games SET payload=?,base_payload=? WHERE id=?').run(JSON.stringify({...JSON.parse(row.payload),gameplay:p}),JSON.stringify({...JSON.parse(row.base_payload),gameplay:p}),c.gameId);}
sqlite.prepare('INSERT INTO catalog_overrides(game_id,field,value,updated_at) VALUES(?,?,?,?)').run(manual.gameId,'gameplay',JSON.stringify(manual.gameplay),'2026-10-10');
sqlite.prepare('INSERT INTO library(user_id,game_id,status,note,rating,updated_at) VALUES(?,?,?,?,?,?)').run('owner',first.gameId,'playing','Özel not',5,'2026-10-10');
const before=sqlite.prepare('SELECT * FROM catalog_games ORDER BY id').all();
const tables=['library','lists','list_games','catalog_overrides','catalog_scores','catalog_source_ids','catalog_media','catalog_game_genres','catalog_game_tags','catalog_game_platforms','catalog_game_systems','catalog_search_terms'];const untouched=new Map(tables.map(t=>[t,sqlite.prepare('SELECT * FROM '+t+' ORDER BY rowid').all()]));
const sync=await moduleFor('lib/gameplay-sync.ts');await moduleFor('lib/gameplay-schema.ts').then(m=>m.ensureGameplaySchema(database));const batch=database.batch;let attempt=0;
// Schema creation remains successful; fail the subsequent atomic data batch.
database.batch=async statements=>{if(statements.some(s=>s.sql.includes('UPDATE catalog_bootstrap SET stage=')))return batch([...statements,database.prepare('INSERT INTO nonexistent_gameplay_test VALUES(1)')]);return batch(statements);};
await assert.rejects(sync.ensureGameplay(database));assert.equal(sqlite.prepare("SELECT cursor FROM catalog_bootstrap WHERE stage='gameplay'").get().cursor,'0');assert.deepEqual(sqlite.prepare('SELECT * FROM catalog_games ORDER BY id').all(),before);
let raced=false;database.batch=async statements=>{if(!raced&&statements.some(s=>s.sql.includes('UPDATE catalog_bootstrap SET stage='))){raced=true;const saved=sqlite.prepare('SELECT payload,base_payload FROM catalog_games WHERE id=?').get(first.gameId);const base={...JSON.parse(saved.base_payload),desc:'Eşzamanlı düzenleme'},game={...JSON.parse(saved.payload),desc:'Eşzamanlı düzenleme'};sqlite.prepare('UPDATE catalog_games SET base_payload=?,payload=?,content_hash=? WHERE id=?').run(JSON.stringify(base),JSON.stringify(game),'concurrent-edit',first.gameId);const expected=before.find(r=>r.id===first.gameId);expected.base_payload=JSON.stringify(base);expected.payload=JSON.stringify(game);}return batch(statements);};
let state=await sync.ensureGameplay(database);assert.equal(state.processed,0);assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM catalog_games WHERE id=?').get(first.gameId).payload).desc,'Eşzamanlı düzenleme');database.batch=batch;
state=await sync.ensureGameplay(database);assert(state.processed>0&&state.processed<=20&&!state.ready);for(;attempt<100&&!state.ready;attempt++)state=await sync.ensureGameplay(database);assert(state.ready);assert.equal(state.processed,data.changes.length);
const clean=raw=>{const g=JSON.parse(raw);delete g.gameplay;delete g.gameplayHistory;return g;};
for(const r of before){const after=sqlite.prepare('SELECT * FROM catalog_games WHERE id=?').get(r.id);assert.deepEqual(clean(after.payload),clean(r.payload));assert.deepEqual(clean(after.base_payload),clean(r.base_payload));for(const k of ['id','steam_app_id','status','sort_order','source_priority','score_value','score_count','score_platform','steam_positive_percent','steam_total'])if(k in r)assert.equal(after[k],r[k],r.id+':'+k);}
for(const [t,rows]of untouched)assert.deepEqual(sqlite.prepare('SELECT * FROM '+t+' ORDER BY rowid').all(),rows,t);
assert(JSON.parse(sqlite.prepare('SELECT payload FROM catalog_games WHERE id=?').get(first.gameId).payload).gameplayHistory.some(p=>JSON.stringify(p)===JSON.stringify(old)));
const revision=sqlite.prepare("SELECT value FROM catalog_meta WHERE id='revision'").get().value;await sync.ensureGameplay(database);assert.equal(sqlite.prepare("SELECT value FROM catalog_meta WHERE id='revision'").get().value,revision);
const repository=await moduleFor('lib/catalog-repository.ts');
for(const keys of [['coop'],['coop','coop-online'],['single','coop-local'],['pvp','pvp-online'],['coop-lan'],['remote-play-together']]){const expected=sqlite.prepare(`SELECT COUNT(*) AS n FROM catalog_games g WHERE g.status='published' AND ${keys.map(()=> 'EXISTS(SELECT 1 FROM catalog_game_features f WHERE f.game_id=g.id AND f.feature=?)').join(' AND ')}`).get(...keys).n;const result=await repository.queryCatalog({gameplay:keys,pageSize:60});assert.equal(result.total,expected);assert(result.games.every(g=>keys.every(k=>g.gameplay.features[k]===true)));}
const parsed=repository.parseCatalogQuery(new URLSearchParams('genre=Aksiyon&genre=Korku&tag=19&tag=1667&play=coop&play=coop-online&play=coop'));assert.deepEqual(parsed.gameplay,['coop','coop-online']);const zero=await repository.queryCatalog({...parsed,tags:[999999999]});assert.equal(zero.total,0);assert.deepEqual(zero.games,[]);assert.throws(()=>repository.parseCatalogQuery(new URLSearchParams('play=hdr')));
const combined=await repository.queryCatalog({genres:['Aksiyon'],tags:[19],gameplay:['single'],steamMin:50,pageSize:60});assert(combined.total>0);assert(combined.games.every(g=>g.genres.includes('Aksiyon')&&g.steamTags.tags.some(t=>t.id===19)&&g.gameplay.features.single===true&&g.steamReview.positivePercent>=50));
const ingest=await moduleFor('lib/catalog-ingest.ts'),newApp=99887766,newId='steam-99887766',newName='Yeni filtre adayı';const newProfile=parseSteamGameplay({steam_appid:newApp,type:'game',name:newName,categories:[{id:2,description:'Single-player'},{id:48,description:'LAN Co-op'}]},newApp);await ingest.ingestGames(database,[{id:newId,name:newName,steamAppId:newApp,platforms:['PC'],pcSystems:['Windows'],genres:['Aksiyon','Korku'],steamTags:{steamAppId:newApp,identityTitle:newName,tags:[{id:19,name:'Action'},{id:1667,name:'Horror'}]},gameplay:newProfile}],{priority:30});const fresh=await repository.queryCatalog({genres:['Aksiyon','Korku'],tags:[19,1667],gameplay:['single','coop','coop-lan'],q:newName});assert.equal(fresh.total,1);assert.equal(fresh.games[0].id,newId);await ingest.ingestGames(database,[{id:newId,name:newName,steamAppId:newApp,platforms:['PC'],genres:['Aksiyon','Korku'],desc:'Kaynak güncellemesi'}]);assert.deepEqual((await repository.gamesByIds([newId]))[0].gameplay,newProfile,'Updates with missing gameplay data preserve verified features');assert(sqlite.prepare('SELECT 1 FROM catalog_game_features WHERE game_id=? AND feature=?').get(newId,'coop-lan'));
const plan=sqlite.prepare('EXPLAIN QUERY PLAN SELECT game_id FROM catalog_game_features WHERE feature=?').all('coop');assert(plan.some(r=>String(r.detail).includes('catalog_game_features_filter_idx')));f.close();console.log('Passed: verified feature identities, generic/subtype/unknown semantics, RPT separation, bounded atomic migration, history/manual precedence, rollback/races/resume/idempotency, unchanged scores/media/private data, indexed AND queries and exact zero results.');
