const vm=require('node:vm'),assert=require('node:assert/strict');
const {createHarness}=require('./frontend-harness.cjs');
(async()=>{
 const {ctx,elements:e,listeners,source}=createHarness();
 const run=code=>vm.runInContext(code,ctx);
 await new Promise(r=>setTimeout(r,30));
 await run("openGame('"+source.find(g=>g.name==='Kenshi').id+"')");
 await new Promise(r=>setTimeout(r,5));
 assert(e.detailContent.innerHTML.includes('id="mediaViewport"'));
 assert.equal(e.mediaStageNav.hidden,false);
 assert.equal(e.mediaPrev.hidden,false);
 const click=id=>listeners.click({target:{closest:q=>q==='button'?e[id]:null}});
 click('mediaOverlayNext');assert.equal(e.mediaCount.textContent,'2 / 2');
 assert(e.mediaStrip.innerHTML.includes('data-media-index="1" aria-label="Screenshot · Görsel" aria-pressed="true"'));
 click('mediaOverlayNext');assert.equal(e.mediaCount.textContent,'1 / 2');
 click('mediaOverlayPrev');assert.equal(e.mediaCount.textContent,'2 / 2');
 click('mediaStage');assert.equal(e.mediaCount.textContent,'2 / 2');
 let prevented=0;
 listeners.keydown({target:{closest:q=>q==='#mediaGallery'?e.mediaGallery:null},key:'ArrowRight',preventDefault(){prevented++}});
 assert.equal(e.mediaCount.textContent,'1 / 2');assert.equal(prevented,1);
 listeners.keydown({target:{closest:q=>q==='#mediaGallery'?e.mediaGallery:q==='video,input,select,textarea'?{}:null},key:'ArrowRight',preventDefault(){throw Error('Video kontrolü engellendi')}});
 assert.equal(e.mediaCount.textContent,'1 / 2');
 let fullscreen=0;e.mediaViewport.requestFullscreen=()=>{fullscreen++;return Promise.resolve()};
 click('mediaExpand');assert.equal(fullscreen,1);
 let resolveHls,created=0,destroyed=0;
 ctx.Hls=class{static Events={ERROR:'error',MANIFEST_PARSED:'manifest'};static isSupported(){return true}constructor(){created++}on(){}attachMedia(){}loadSource(){}destroy(){destroyed++}};
 ctx.delayedHls=new Promise(r=>resolveHls=r);
 run('loadHls=()=>delayedHls');
 const oldPlay=run('playMedia()');const oldVideo=e.mediaVideo;
 run('selectMedia(1);selectMedia(0)');
 const newPlay=run('playMedia()');
 resolveHls(ctx.Hls);await Promise.all([oldPlay,newPlay]);
 assert.equal(created,1);assert(oldVideo.paused);
 run('selectMedia(1)');assert.equal(destroyed,1);assert.equal(run('mediaVideo'),null);
 run("mediaFailure('Test hatası')");assert.equal(e.mediaStageNav.hidden,false);
 click('mediaOverlayPrev');assert(e.mediaStage.innerHTML.includes('Fragmanı oynat'));
 run('activeMedia.items=activeMedia.items.slice(0,1);selectMedia(0)');
 assert.equal(e.mediaStageNav.hidden,true);assert.equal(e.mediaPrev.hidden,true);assert.equal(e.mediaNext.disabled,true);
 assert(e.mediaStrip.innerHTML.includes('data-media-index="0"'));
 listeners.keydown({target:{closest:()=>e.mediaGallery},key:'ArrowRight',preventDefault(){throw Error('Tek medya gereksiz gezinme')}});
 run('activeMedia.items=[];updateMediaNavigation()');assert.equal(e.mediaStageNav.hidden,true);
 run('closeMedia();stopSpotlight();clearTimeout(spotlightRefreshTimer)');
 console.log('Passed: overlay/bottom navigation, wrap, thumbnails/count, keyboard/video controls, fullscreen, single/empty states, playback cleanup and rapid HLS race.');
})().catch(err=>{console.error(err);process.exitCode=1});
