import fs from 'node:fs';
import {strict as assert} from 'node:assert';
import {metacriticResource,metacriticScoreForGame} from '../lib/metacritic-identity.mjs';
import {buildScoreCatalog} from '../scripts/refresh-metacritic-scores.mjs';
const read=name=>JSON.parse(fs.readFileSync(name,'utf8'));
const games=read('data/catalog.json'), identities=read('data/game-identities.json'), records=read('data/metacritic-users.json');
const helldivers=games.find(g=>g.steamAppId===553850), link=identities[helldivers.id], record=records[link.scoreRecordId];
assert.equal(record.score,7.5);assert.equal(record.metacriticNumericId,'1300595968');
for(const name of ['HELLDIVERS™ 2','Helldivers 2','Helldivers II','Entirely renamed display title']) assert.equal(metacriticScoreForGame({...helldivers,name},identities,records)?.score,7.5,'Display names must not participate in joins');
assert.equal(metacriticScoreForGame({...helldivers,steamAppId:730},identities,records),null);
assert.equal(metacriticScoreForGame({...helldivers,id:'invented-id'},identities,records),null);
for(const patch of [{metacriticId:'counter-strike-global-offensive'},{recordId:'another-record'},{metacriticNumericId:'1300000000'},{platform:'PC'},{metric:'critic-score'},{score:82},{url:'https://attacker.example/game/helldivers-2/'}]) assert.equal(metacriticScoreForGame(helldivers,identities,{...records,[record.recordId]:{...record,...patch}}),null);
assert.equal(metacriticResource('http://www.metacritic.com/game/pc/helldivers-2?ftag=x').id,'helldivers-2');
assert.equal(metacriticResource('https://www.metacritic.com/game/overcooked%21-2/').id,'overcooked!-2');
const overcooked=games.find(g=>g.steamAppId===728880);assert.equal(metacriticScoreForGame(overcooked,identities,records).score,7.5,'Legacy URL punctuation must preserve the reviewed resource alias');
for(const url of ['https://metacritic.com.evil.example/game/a/','https://user:pass@www.metacritic.com/game/a/','https://www.metacritic.com:444/game/a/','https://www.metacritic.com/movie/a/','javascript:alert(1)']) assert.equal(metacriticResource(url),null);

const fixtureGames=[{id:'game-a',steamAppId:10,name:'Name unrelated to source URL'}];
const input={snapshotDate:'2026-10-05',sourceUrl:'https://github.com/leinstay/steamdb',rows:[{sourceRecordId:41,sourceKind:'steam',steamAppId:10,metacriticUrl:'https://www.metacritic.com/game/old-url/',userScore:8.2}]};
const evidence={previousApproved:{},manualReviews:[],editionAudit:[],steam:[],wikidata:[{steamAppId:10,qid:'Q10',metacriticId:'old-url',metacriticNumericId:'1300000001'},{steamAppId:10,qid:'Q10',metacriticId:'new-url',metacriticNumericId:'1300000001'}]};
let built=buildScoreCatalog(fixtureGames,input,evidence);
assert.equal(metacriticScoreForGame(fixtureGames[0],built.identities,built.records).score,8.2,'Same numeric ID establishes a URL alias without title similarity');
const blocked={...evidence,editionAudit:[{steamAppId:10,status:'reject_current_resource',currentCandidateSlug:'old-url',rationale:'Store app ID reused for a successor'}]};
built=buildScoreCatalog(fixtureGames,input,blocked);assert.equal(built.report.userScores,0,'A reused app ID cannot bypass an edition rejection');
const noUser={...input,rows:[{...input.rows[0],userScore:null,criticScore:99}]};
built=buildScoreCatalog(fixtureGames,noUser,evidence);assert.equal(built.report.userScores,0,'Critic score must never become a user score');
const foreign={...input,rows:[{...input.rows[0],steamAppId:20,sourceKind:'gog_exclusive'}]};
built=buildScoreCatalog(fixtureGames,foreign,evidence);assert.equal(built.report.userScores,0,'Resource overlap alone does not authorize borrowing another store row');
built=buildScoreCatalog(fixtureGames,foreign,{...evidence,supplementalRecords:[{steamAppId:10,sourceRecordId:41,metacriticId:'new-url',sourceUrl:'https://api.gog.com/products/1'}]});assert.equal(built.report.userScores,1,'An explicitly reviewed record-ID crosslink can supplement a missing store row');

// A correctly joined secondary dataset with no score still needs a numerical source.
const primaryFact={recordId:'mc-user:reviewed:10:PC:2026-10-06',gameId:'game-a',steamAppId:10,metacriticId:'new-url',metacriticNumericId:'1300000001',metric:'user-score',platform:'PC',score:7.8,userRatings:507,sourceUrl:'https://www.metacritic.com/game/new-url/?platform=pc',retrievedAt:'2026-10-06T14:00:00Z',snapshotDate:'2026-10-06',scoreDate:null,provenance:{method:'user-supplied-capture',metricLabel:'User score',platformLabel:'PC',captureSha256:'a'.repeat(64)}};
const reviewed={schemaVersion:1,facts:[primaryFact]};
built=buildScoreCatalog(fixtureGames,noUser,evidence,reviewed);
assert.equal(metacriticScoreForGame({...fixtureGames[0],name:'Renamed again'},built.identities,built.records).score,7.8,'Correct external IDs plus a reviewed primary fact fill a secondary coverage gap');
assert.equal(built.report.sourceCoverage.reviewedPrimaryScores,1);assert.equal(built.records[primaryFact.recordId].platform,'PC');assert.equal(built.records[primaryFact.recordId].scoreDate,null);
built=buildScoreCatalog(fixtureGames,input,evidence,reviewed);assert.equal(built.records[primaryFact.recordId].score,7.8,'Explicit reviewed PC fact is preferred to a platform-unspecified secondary fact');
for(const patch of [{gameId:'other-game'},{steamAppId:20},{metacriticNumericId:'1300999999'},{metric:'critic-score',score:82},{metric:'positive-rating-percent',score:7.2},{platform:'PlayStation 5'},{sourceUrl:'https://www.metacritic.com/game/new-url/?platform=ps5'},{sourceUrl:'https://www.metacritic.com/game/new-url/?platform=pc&platform=ps5'},{sourceUrl:'https://www.metacritic.com/game/other-game/'},{sourceUrl:'https://evil.example/game/new-url/'},{score:null},{score:72},{userRatings:0},{scoreDate:'2026-10-06'},{provenance:{method:'public-primary-cache',metricLabel:'User score',platformLabel:'PC',pageHeading:'PC User Reviews'}}])assert.throws(()=>buildScoreCatalog(fixtureGames,noUser,evidence,{schemaVersion:1,facts:[{...primaryFact,...patch}]}),/Invalid reviewed score|approved external ID/);
assert.throws(()=>buildScoreCatalog(fixtureGames,noUser,evidence,{schemaVersion:1,facts:[primaryFact,primaryFact]}),/duplicate/);
assert.throws(()=>buildScoreCatalog(fixtureGames,noUser,blocked,reviewed),/approved external ID/,'A primary value must not bypass an excluded work identity');
built=buildScoreCatalog(fixtureGames,noUser,evidence);assert.equal(built.report.missing[0].sourceGap,'approved_identity_without_score_fact');assert.equal(built.report.missing[0].metacriticScoreAvailability,'not_established','A missing imported fact does not mean Metacritic lacks a score');
const mortal=games.find(g=>g.steamAppId===2584270),mortalScore=metacriticScoreForGame(mortal,identities,records);
assert.equal(mortalScore.score,7.8);assert.equal(mortalScore.userRatings,507);assert.equal(mortalScore.platform,'PC');assert.equal(mortalScore.metacriticNumericId,'1300689309');assert.equal(mortalScore.provenance.method,'user-supplied-capture');
assert.equal(new URL(mortalScore.url).searchParams.get('platform'),'pc','Primary score links retain the selected platform');for(const url of [mortalScore.url.replace('platform=pc','platform=ps5'),mortalScore.url+'&platform=ps5'])assert.equal(metacriticScoreForGame(mortal,identities,{...records,[mortalScore.recordId]:{...mortalScore,url}}),null);
const report=read('data/METACRITIC-REPORT.json');
assert.equal(report.initiallyMissingAudited,546);assert.equal(report.userScores+report.remainingMissing,games.length);
assert.equal(report.userScores,report.previousUserScores+report.recoveredUserScores-report.removedInvalidMappings);
assert.equal(Object.values(report.sourceCoverage.missingByStatus).reduce((a,b)=>a+b,0),report.remainingMissing);
assert.equal(report.sourceCoverage.secondaryDatasetScores+report.sourceCoverage.historicalWikidataScores+report.sourceCoverage.reviewedPrimaryScores,report.userScores);
console.log('Passed: ID joins, aliases and edition exclusions; primary numerical coverage fallback, fact provenance / metric / platform checks, Mortal Shell II regression and coverage reconciliation.');
