import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {buildScoreCatalog} from '../scripts/refresh-metacritic-scores.mjs';
import {metacriticScoreForGame} from '../lib/metacritic-identity.mjs';
import {validatePrimaryScoreFact} from '../lib/metacritic-platform.mjs';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
import harness from './frontend-harness.cjs';
const game={id:'policy-fixture',steamAppId:99000004,name:'Policy Fixture',genres:['Macera'],platforms:['PC'],pcSystems:['Windows'],desc:'Korunan açıklama'};
const evidence={previousApproved:{},manualReviews:[{steamAppId:game.steamAppId,status:'approved',metacriticId:'policy-fixture',numericId:null,evidenceURLs:['https://www.metacritic.com/game/policy-fixture/'],reviewedAt:'2026-10-08',rationale:'İncelenen doğrudan birincil kaynak kimliği'}],editionAudit:[],steam:[],wikidata:[]};
const empty={snapshotDate:'2026-10-08',rows:[]};
const ps5={recordId:'mc-user:reviewed:99000004:PS5:2026-10-08',gameId:game.id,steamAppId:game.steamAppId,metacriticId:'policy-fixture',metacriticNumericId:null,metric:'user-score',platform:'PlayStation 5',score:8.4,userRatings:635,sourceUrl:'https://www.metacritic.com/game/policy-fixture/user-reviews/?platform=playstation-5',retrievedAt:'2026-10-08T11:00:00Z',snapshotDate:'2026-10-08',scoreDate:null,provenance:{method:'public-primary-cache',metricLabel:'User score',platformLabel:'PlayStation 5',pageHeading:'PlayStation 5 User Reviews',sourceCrawlLabel:'last month',retrievalReference:'turn23view0'}};
let result=buildScoreCatalog([game],empty,evidence,{schemaVersion:1,facts:[ps5]});
const score=metacriticScoreForGame(game,result.identities,result.records);assert.equal(score.score,8.4);assert.equal(score.platform,'PlayStation 5');assert.equal(new URL(score.url).searchParams.get('platform'),'playstation-5');
assert.equal(result.report.userScores,1,'No Steam link or SteamDB score is needed after a reviewed Metacritic identity');
const pc={...ps5,recordId:'mc-user:reviewed:99000004:PC:2026-10-08',platform:'PC',score:7.5,sourceUrl:ps5.sourceUrl.replace('playstation-5','pc'),provenance:{...ps5.provenance,platformLabel:'PC',pageHeading:'PC User Reviews'}};
for(const facts of [[ps5,pc],[pc,ps5]]){result=buildScoreCatalog([game],empty,evidence,{schemaVersion:1,facts});assert.equal(result.identities[game.id].scorePlatform,'PC','An available reviewed PC score takes precedence');}
for(const patch of [{sourceUrl:ps5.sourceUrl.replace('playstation-5','pc')},{platform:'PC'},{metric:'critic-score'},{score:84},{userRatings:123,provenance:{...ps5.provenance,metricLabel:'Metascore'}}])assert.throws(()=>validatePrimaryScoreFact({...ps5,...patch}));
const overview={...ps5,sourceUrl:'https://www.metacritic.com/game/policy-fixture/',provenance:{...ps5.provenance,pageHeading:'Game overview',platformEvidenceUrl:ps5.sourceUrl,platformEvidenceReference:'turn23view0'}};
validatePrimaryScoreFact(overview);
const unspecified={...ps5,platform:null,sourceUrl:'https://www.metacritic.com/game/policy-fixture/',provenance:{...ps5.provenance,platformLabel:null,pageHeading:'Game overview',platformUnverified:true}};
validatePrimaryScoreFact(unspecified);
const unspecifiedResult=buildScoreCatalog([game],empty,evidence,{schemaVersion:1,facts:[unspecified]});
assert.equal(metacriticScoreForGame(game,unspecifiedResult.identities,unspecifiedResult.records).score,8.4);
assert.equal(new URL(metacriticScoreForGame(game,unspecifiedResult.identities,unspecifiedResult.records).url).searchParams.has('platform'),false);
assert.throws(()=>validatePrimaryScoreFact({...unspecified,provenance:{...unspecified.provenance,metricLabel:'Metascore'}}));
assert.throws(()=>validatePrimaryScoreFact({...unspecified,sourceUrl:ps5.sourceUrl}));
const single={...pc,sourceUrl:unspecified.sourceUrl,provenance:{...pc.provenance,pageHeading:'Game overview',platformEvidenceKind:'single-platform',platformEvidencePlatforms:['PC'],platformEvidenceUrl:unspecified.sourceUrl,platformEvidenceReference:'turn23view0'}};
validatePrimaryScoreFact(single);
assert.throws(()=>validatePrimaryScoreFact({...single,provenance:{...single.provenance,platformEvidencePlatforms:['PC','PlayStation 5']}}));
const historical={...pc,userRatings:null,provenance:{method:'public-historical-dataset',metricLabel:'User score',platformLabel:'PC',datasetCollectedAt:'2025-10-07',datasetBlobSha:'13385d1faf43adddc792ec771595763396261378',datasetUrl:'https://github.com/StadynR/metacritic-reviews-dataset/blob/13385d1faf43adddc792ec771595763396261378/metacritic_dataset_raw.csv',datasetRow:{name:'Policy Fixture',platform:'PC',user_score:'7.5',developer:'Fixture Studio',release_date:'2025-01-01'}}};
validatePrimaryScoreFact(historical);
const historyResult=buildScoreCatalog([game],empty,evidence,{schemaVersion:1,facts:[historical]});
assert.equal(metacriticScoreForGame(game,historyResult.identities,historyResult.records).provenance.datasetCollectedAt,'2025-10-07');
assert.equal(metacriticScoreForGame(game,historyResult.identities,historyResult.records).scoreDate,null);
for(const patch of [{score:7.6},{userRatings:1},{provenance:{...historical.provenance,datasetCollectedAt:'2027-01-01'}},{provenance:{...historical.provenance,datasetRow:{...historical.provenance.datasetRow,platform:'PlayStation 5'}}},{provenance:{...historical.provenance,datasetUrl:'https://example.com/dataset.csv'}}])assert.throws(()=>validatePrimaryScoreFact({...historical,...patch}));
assert.throws(()=>validatePrimaryScoreFact({...overview,provenance:{...overview.provenance,platformEvidenceUrl:'https://evil.example/game/policy-fixture/user-reviews/?platform=playstation-5'}}));
assert.throws(()=>validatePrimaryScoreFact({...overview,provenance:{...overview.provenance,platformEvidenceUrl:ps5.sourceUrl.replace('/policy-fixture/','/other-edition/')}}));

const fixture=createCatalogFixture();await readyCatalog(await moduleFor('lib/catalog-bootstrap.ts'));
const ingest=await moduleFor('lib/catalog-ingest.ts');await ingest.ingestGames(fixture.database,[{...game,metacriticUser:score}]);
const repository=await moduleFor('lib/catalog-repository.ts');
const page=await repository.queryCatalog(repository.parseCatalogQuery(new URLSearchParams('q=Policy+Fixture&rating=8&sort=rating')),null,fixture.database);
assert.equal(page.total,1);assert.equal(page.games[0].metacriticUser.platform,'PlayStation 5');
assert.equal(fixture.sqlite.prepare('SELECT edition_id FROM catalog_scores WHERE record_id=?').get(score.recordId).edition_id,null,'A console observation is not labeled as a PC edition score');fixture.close();
const h=harness.createHarness();for(let n=0;n<100&&!vm.runInContext('state.loaded',h.ctx);n++)await new Promise(r=>setTimeout(r,10));
h.ctx.policyGame={...game,metacriticUser:score};
assert.equal(vm.runInContext('userScore(policyGame).score',h.ctx),8.4);
assert(vm.runInContext('scoreBadge(policyGame)',h.ctx).includes('PlayStation 5'));
assert(vm.runInContext('scoreDetails(policyGame)',h.ctx).includes('635'));
const kenshi=h.games.find(g=>g.id==='kenshi');h.ctx.secondGame=kenshi;
await vm.runInContext('rememberGames([policyGame,secondGame]);state.compare=new Set([policyGame.id,secondGame.id]);showCompare()',h.ctx);
assert(h.elements.compareContent.innerHTML.includes('8,4/10'));assert(h.elements.compareContent.innerHTML.includes('PlayStation 5'));
vm.runInContext('closeMedia();stopSpotlight();clearTimeout(spotlightRefreshTimer)',h.ctx);
console.log('Passed: direct Metacritic ID without Steam crosslink, platform fallback and PC preference, source/metric guards, SQL filtering, correct edition provenance and UI/detail/comparison.');
