import fs from 'node:fs';
import {strict as assert} from 'node:assert';
import {createCatalogFixture,moduleFor,readyCatalog} from './catalog-fixture.mjs';
const seed=JSON.parse(fs.readFileSync('data/catalog.json'));
const fixture=createCatalogFixture(),sqlite=fixture.sqlite;
await readyCatalog(await moduleFor('lib/catalog-bootstrap.ts'));
const {ingestGames}=await moduleFor('lib/catalog-ingest.ts');
const {localRelatedForGame}=await moduleFor('lib/related.ts');
const {gameById,gamesByIds,queryCatalog}=await moduleFor('lib/catalog-repository.ts');
const recommend=async game=>(await localRelatedForGame(game,fixture.database)).map(r=>r.game);
const now=Date.parse('2026-10-06T12:00:00Z');let nextId=9900000;
const make=(id,tags,extra={})=>{const steamAppId=nextId++;return {id,name:id,genres:['RPG'],platforms:['PC'],steamAppId,steamTags:{steamAppId,identityTitle:id,tags:tags.map((t,i)=>({id:t,name:'Tag '+t,count:1000-i*10})),sourceKind:'steam-store',retrievedAt:'2026-10-06T10:00:00Z'},...extra};};
const target=make('target',[901,902,903,19,4182]);
const close=[...Array(30)].map((_,i)=>make('close-'+String(i).padStart(2,'0'),[901,902,903,19,4182]));
const weak=make('new-weak',[901,902,9991,9992],{catalogAddedAt:new Date(now-1000).toISOString()});
const unrelated=make('new-unrelated',[811,812,19,4182],{catalogAddedAt:new Date(now).toISOString()});
const fixtures=[target,...close,weak,unrelated,make('archived',[901,902,903],{catalogScope:'archive'}),make('console',[901,902,903],{platforms:['PlayStation']})];
await ingestGames(fixture.database,fixtures);
let results=await recommend(target);
assert.equal(results.length,20);assert.equal(new Set(results.map(g=>g.id)).size,20);
assert(!results.some(g=>['target','new-unrelated','archived','console','new-weak'].includes(g.id)),'Newness cannot override detailed-tag relevance');
const fresh=make('aaa-new-strong',[901,902,903,19,4182],{genres:['Yarış'],catalogAddedAt:new Date(now-1000).toISOString()});
await ingestGames(fixture.database,[fresh]);results=await recommend(target);
assert(results.some(g=>g.id===fresh.id),'A new matching game must enter the top20 irrespective of broad genre');assert.equal(results[0].id,fresh.id);
sqlite.prepare("UPDATE catalog_games SET status='archived' WHERE id=?").run(fresh.id);
assert(!(await recommend(target)).some(g=>g.id===fresh.id));
assert.equal((await recommend(make('generic-only',[19,4182]))).length,0,'Action and Singleplayer alone do not establish similarity');
assert.equal((await recommend({...target,steamTags:null})).length,0);
assert.equal((await recommend({...target,steamTags:{...target.steamTags,identityTitle:'Different game'}})).length,0);
const twenty=Array.from({length:20},(_,i)=>4000+i),target21=make('target-21',[...twenty,7000,7001]),candidate21=make('outside-top20',[7000,7001]);
await ingestGames(fixture.database,[target21,candidate21]);assert.equal((await recommend(target21)).length,0,'Tags outside highest20 cannot influence the match');
const order=(await recommend(target)).map(g=>g.id);
await ingestGames(fixture.database,fixtures.map(g=>({...g,metacriticUser:{recordId:'fixture-score-'+g.id,metacriticId:'fixture-'+g.id,metric:'user-score',score:Math.random()*10,platform:null}})));
assert.deepEqual((await recommend(target)).map(g=>g.id),order,'Metacritic score cannot affect related ranking');
const invalid=make('invalid-profile',[901,902,903,19,4182]);invalid.steamTags.identityTitle='Another game';await ingestGames(fixture.database,[invalid]);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM catalog_game_tags WHERE game_id=?').get(invalid.id).n,0);assert(!(await recommend(target)).some(g=>g.id===invalid.id));
const valheim=await gameById(seed.find(g=>g.name==='Valheim').id),matches=await localRelatedForGame(valheim,fixture.database);
assert.equal(matches.length,20);assert(matches.every(m=>m.game.id!==valheim.id&&m.shared.length>=2&&m.score>0&&m.score<=1.000001));assert(matches.every((m,i)=>i===0||m.score<=matches[i-1].score));
assert.deepEqual(matches.map(m=>m.game.id),(await localRelatedForGame(valheim,fixture.database)).map(m=>m.game.id));
// Independently check a small, analytically solvable weighted Jaccard case.
const math=createCatalogFixture();
const weighted=(id,app,tags)=>({id,name:id,steamAppId:app,genres:['RPG'],platforms:['PC'],steamTags:{steamAppId:app,identityTitle:id,tags:tags.map(([tag,count])=>({id:tag,name:'Math '+tag,count}))}});
const mathTarget=weighted('math-target',9999101,[[90000001,100],[90000002,25]]),identical=weighted('math-identical',9999102,[[90000001,100],[90000002,25]]),extra=weighted('math-extra',9999103,[[90000001,100],[90000002,25],[90000003,100]]);
await ingestGames(math.database,[mathTarget,identical,extra]);
const calculated=await localRelatedForGame(mathTarget,math.database);
assert.equal(calculated[0].game.id,identical.id);assert(Math.abs(calculated[0].score-1)<1e-10);
const expected=(1+Math.sqrt(25/100))/(1+Math.sqrt(25/100)+(1+Math.log(4/2)));
assert(Math.abs(calculated.find(r=>r.game.id===extra.id).score-expected)<1e-10,'SQL must retain weighted Jaccard and rarity math');
math.close();globalThis.testDb=fixture.database;
console.log('Passed: SQL highest20 tags/games, new matching additions, no forced-new promotion, removal, self/archive/console exclusion, source identity, score independence and deterministic Valheim ranking.');
const {addSourceGame,refreshSelected}=await moduleFor('lib/catalog.ts');
const snak=value=>({rank:'normal',mainsnak:{snaktype:'value',datavalue:{value}}}),steamId=9999001;
assert(!seed.some(g=>g.steamAppId===steamId));
const steam={name:'New matching fixture',type:'game',platforms:{windows:true},release_date:{coming_soon:false,date:'Jan 2, 2025'},genres:[{description:'RPG'}],developers:['Fixture Studio'],header_image:'https://cdn.akamai.steamstatic.com/steam/apps/'+steamId+'/header.jpg',supported_languages:'English',categories:[]};
let tagPageAvailable=true;
const primaryTags=Array.from({length:24},(_,i)=>({tagid:8500+i,name:'Fixture Tag '+i,count:200-i,browseable:true}));
const tagHtml='<div id="appHubAppName">'+steam.name+'</div><script>InitAppTagModal('+steamId+','+JSON.stringify(primaryTags)+',[])</script>';
globalThis.fetch=async url=>{if(String(url).includes('/api/appdetails'))return Response.json({[steamId]:{success:true,data:steam}});if(String(url).includes('steampowered.com')){if(!tagPageAvailable)throw new Error('Store tag page unavailable');return new Response(tagHtml);}return Response.json({entities:{Q987654321:{labels:{en:{value:steam.name}},claims:{P31:[snak({id:'Q7889'})],P1733:[snak(String(steamId))],P400:[snak({id:'Q1406'})],P136:[snak({id:'Q2762504'})],P577:[snak({time:'+2025-01-02T00:00:00Z',precision:11})]}},Q1406:{labels:{en:{value:'Microsoft Windows'}}},Q2762504:{labels:{en:{value:'role-playing video game'}}}}});};
const totalBefore=(await queryCatalog()).total,added=await addSourceGame('Q987654321');
assert(Number.isFinite(Date.parse(added.catalogAddedAt)));assert.equal(added.steamTags.tags.length,20);assert.equal(added.steamTags.tags[0].id,8500);assert.equal(added.steamTags.steamAppId,steamId);
assert.equal((await queryCatalog()).total,totalBefore+1);assert.equal((await gamesByIds([added.id]))[0].catalogAddedAt,added.catalogAddedAt);assert.equal((await addSourceGame('Q987654321')).catalogAddedAt,added.catalogAddedAt);
await ingestGames(fixture.database,[{...added,catalogAddedAt:'2026-09-01T00:00:00Z'}],{writeLegacy:true});tagPageAvailable=false;const updated=await refreshSelected([added.id]);
assert.deepEqual(updated.games[0].steamTags,added.steamTags);assert.equal(updated.games[0].catalogAddedAt,'2026-09-01T00:00:00Z');assert.equal((await gamesByIds([added.id]))[0].catalogAddedAt,'2026-09-01T00:00:00Z');assert.equal(JSON.parse(sqlite.prepare('SELECT payload FROM source_games WHERE id=?').get(added.id).payload).catalogAddedAt,'2026-09-01T00:00:00Z');
fixture.close();console.log('Passed: actual source addition/ID lookup, highest20 source tags, deduplicated import, original addition date and failed tag refresh preserve verified data and legacy mirror.');
