import {steamGame} from './steam';import {db} from './db';import {safeUrl} from './security';
import {queryCatalog,gamesByIds,baseGamesByIds,gameBySourceId,catalogDatabase,invalidateCatalogMetadata,type CatalogQuery} from './catalog-repository';
import {ingestGames} from './catalog-ingest';
export type Game={id:string;qid?:string;steamAppId?:number|null;name:string;year:number|null;genres:string[];platforms:string[];studio?:string;url?:string;sourceUrl:string;sourceRetrievedAt:string;[key:string]:any};
const cachedId='wikidata-v1';
export function unique<T>(xs:T[]){return [...new Set(xs)];}
function value(e:any,p:string){return (e?.claims?.[p]||[]).filter((c:any)=>c.rank!=='deprecated'&&c.mainsnak?.snaktype==='value').map((c:any)=>c.mainsnak.datavalue.value);}
function entityIds(e:any,p:string):string[]{return value(e,p).map((v:any)=>v.id).filter((v:any)=>/^Q\d+$/.test(v));}
function english(e:any){return e?.labels?.en?.value||e?.labels?.mul?.value||e?.labels?.tr?.value||'';}
export function platformName(label:string){const x=label.toLowerCase();if(/windows|linux|macos|os x|personal computer/.test(x))return 'PC';if(x.includes('playstation'))return 'PlayStation';if(x.includes('xbox'))return 'Xbox';if(x.includes('nintendo switch'))return 'Switch';if(x==='android')return 'Android';if(x==='ios'||x==='ipados')return 'iOS';return null;}
export function genreName(label:string){const x=label.toLowerCase();if(/role-playing|role playing/.test(x))return 'RPG';if(/survival/.test(x))return 'Hayatta kalma';if(/strategy|tactics|tactical/.test(x))return 'Strateji';if(/platform|metroidvania/.test(x))return 'Platform';if(/puzzle/.test(x))return 'Bulmaca';if(/adventure/.test(x))return 'Macera';if(/simulation|simulator|farm life/.test(x))return 'Simülasyon';if(/racing/.test(x))return 'Yarış';if(/sport/.test(x))return 'Spor';if(/shooter|first-person|third-person/.test(x))return 'Nişancı';if(/action|fighting|hack and slash/.test(x))return 'Aksiyon';if(/open.world|sandbox/.test(x))return 'Açık dünya';if(/horror/.test(x))return 'Korku';if(/roguelike|roguelite/.test(x))return 'Roguelike';return null;}
async function api(ids:string[],props:string){const url=new URL('https://www.wikidata.org/w/api.php');url.search=new URLSearchParams({action:'wbgetentities',ids:ids.join('|'),props,languages:'en|tr|mul',format:'json'}).toString();const r=await fetch(url,{headers:{'User-Agent':'NeOynasam/1.0 (open game discovery; CC0 data)'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Kaynak HTTP ${r.status}`);const data:any=await r.json();if(data.error||!data.entities)throw new Error('Kaynak geçerli veri döndürmedi.');return data.entities;}
export async function cached(){try{const c=await db().prepare('SELECT payload,fetched_at AS fetchedAt FROM catalog_cache WHERE id=?').bind(cachedId).first<{payload:string;fetchedAt:string}>();if(c){const payload=JSON.parse(c.payload);return {games:payload.games as Game[],fetchedAt:c.fetchedAt,lastBatch:payload.lastBatch as number};}}catch{}return null;}
/** Kept as a bounded compatibility facade; ordinary requests never assemble all game payloads. */
export async function catalog(query:CatalogQuery={}){return queryCatalog(query);}
export async function knownGame(id:string){return (await gamesByIds([id])).length>0;}
export async function refreshSelected(ids:string[]){
 const database=await catalogDatabase(),selected=(await baseGamesByIds(ids,database)).filter(g=>g.catalogScope!=='archive'&&g.platforms.includes('PC')&&Number.isSafeInteger(g.steamAppId));
 if(!selected.length)throw new Error('Bu kayıtlarda yenilenebilir Steam oyunu yok.');
 const changed:Game[]=[],failed:string[]=[];
 for(const g of selected){try{const patch=await steamGame(Number(g.steamAppId));changed.push({...g,...patch,platforms:unique(['PC',...g.platforms]),url:patch.steamUrl} as Game);}catch{failed.push(g.id);}}
 if(!changed.length)throw new Error('Steam yanıt vermedi; mevcut katalog korunuyor.');
 const stamp=new Date().toISOString();
 const result=await ingestGames(database,changed,{priority:30,writeLegacy:true,tail:[database.prepare('INSERT INTO catalog_cache(id,payload,fetched_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at').bind(cachedId,JSON.stringify({lastBatch:-1}),stamp)]});
 invalidateCatalogMetadata();return {updated:result.updated,games:await gamesByIds(changed.map(g=>g.id),database),failed,fetchedAt:stamp};
}
export async function metadataForQids(qids:string[]){const entities=await api(qids,'claims|labels');const accepted=qids.filter(qid=>entityIds(entities[qid],'P31').includes('Q7889'));const ids=unique(accepted.flatMap(qid=>['P400','P136','P178','P404'].flatMap(p=>entityIds(entities[qid],p))));const labels:any={};for(let i=0;i<ids.length;i+=50)Object.assign(labels,await api(ids.slice(i,i+50),'labels'));return accepted.map(qid=>{const e=entities[qid];const dates=value(e,'P577').filter((v:any)=>v.precision>=9&&/^\+\d{4}-/.test(v.time)).map((v:any)=>Number(v.time.slice(1,5))).filter((y:number)=>y>=1970&&y<=new Date().getUTCFullYear());const genresRaw=entityIds(e,'P136').map(id=>english(labels[id])).filter(Boolean);const platformsRaw=entityIds(e,'P400').map(id=>english(labels[id])).filter(Boolean);return {id:'game-'+qid.toLowerCase(),qid,steamAppId:Number(value(e,'P1733').find((v:any)=>/^\d+$/.test(v)))||null,name:english(e),year:dates.length?Math.min(...dates):null,genres:unique(genresRaw.map(genreName).filter(Boolean)) as string[],platforms:unique(platformsRaw.map(platformName).filter(Boolean)) as string[],studio:entityIds(e,'P178').map(id=>english(labels[id])).filter(Boolean).join(', '),url:value(e,'P856').map(safeUrl).find(Boolean)||'',genresRaw,platformsRaw,modeRaw:entityIds(e,'P404').map(id=>english(labels[id])).filter(Boolean),sourceUrl:`https://www.wikidata.org/wiki/${qid}`,sourceRetrievedAt:new Date().toISOString().slice(0,10),yearSource:'Earliest non-deprecated publication year; can include early access'} as Game;}).filter(g=>g.name);}
export async function sourceSearch(query:string){const url=new URL('https://www.wikidata.org/w/api.php');url.search=new URLSearchParams({action:'wbsearchentities',search:query,language:'en',uselang:'en',type:'item',limit:'10',format:'json'}).toString();const response=await fetch(url,{headers:{'User-Agent':'NeOynasam/1.0 (CC0 game discovery)'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('Kaynağa ulaşılamadı.');const result:any=await response.json();const ids=(result.search||[]).map((r:any)=>r.id).filter((id:string)=>/^Q\d+$/.test(id));if(!ids.length)return [];return (await metadataForQids(ids)).filter(g=>g.platforms.includes('PC'));}
export async function addSourceGame(qid:string){
 const database=await catalogDatabase(),existing=await gameBySourceId('wikidata',qid,database);if(existing)return existing;
 const records=await metadataForQids([qid]);if(!records.length||!records[0].platforms.includes('PC'))throw new Error('Yayımlanmış bir PC oyunu doğrulanamadı.');
 let game=records[0];
 if(game.steamAppId){const same=await gameBySourceId('steam',String(game.steamAppId),database);if(same)return same;const patch=await steamGame(Number(game.steamAppId));game={...game,...patch,id:game.id,qid,platforms:game.platforms,url:patch.steamUrl} as Game;}
 const stamp=new Date().toISOString();game={...game,catalogAddedAt:stamp};
 const last=await database.prepare("SELECT COALESCE(MAX(sort_order),-1)+1 AS next FROM catalog_games WHERE status='published'").first<{next:number}>();
 await ingestGames(database,[game],{priority:30,sortOrder:last?.next||0,writeLegacy:true});invalidateCatalogMetadata();return (await gamesByIds([game.id],database))[0];
}
