import {gameplayKeys,preserveGameplay} from './steam-gameplay.mjs';
import {ensureGameplaySchema} from './gameplay-schema';
import {preserveSteamReviewHistory} from './steam-reviews.mjs';
import {applyOverrides,projectionDefaults,contentHash,normalizeSearch,normalizedTags,normalizedMedia,scoreCount,searchTokens,validCatalogGame,validScore,type CatalogGame} from './catalog-normalize';
export type BootstrapGate={id:string;stage:string;cursor:string;token:string};
export type IngestOptions={priority?:number;sortOrder?:number;status?:'published'|'archived';labels?:Record<string,string>;gate?:BootstrapGate;writeLegacy?:boolean;tail?:D1PreparedStatement[];scoreOnly?:boolean};
const rowTables:Record<string,string[]>={catalog_games:['id','status','name','name_search','year','steam_app_id','studio','payload','base_payload','content_hash','score_value','score_count','score_date','score_platform','catalog_added_at','sort_order','revision','source_priority','updated_at','mood','steam_positive_percent','has_turkish','has_coop','cover_present','tag_profile_complete'],catalog_editions:['id','game_id','edition_key','platform','payload'],catalog_source_ids:['source','external_id','game_id','edition_id','source_url','retrieved_at'],catalog_scores:['record_id','game_id','edition_id','metric','value','platform','rating_count','score_date','retrieved_at','source_url','payload'],catalog_genres:['id','name'],catalog_game_features:['game_id','feature','source','retrieved_at'],catalog_game_genres:['game_id','genre_id'],catalog_tags:['id','name','label'],catalog_game_tags:['game_id','tag_id','weight','rank'],catalog_game_systems:['game_id','system'],catalog_game_platforms:['game_id','platform'],catalog_search_terms:['token','game_id'],catalog_media:['game_id','media_id','kind','url','position','source','retrieved_at','payload']};
function gateSql(gate?:BootstrapGate){return gate?{sql:'EXISTS(SELECT 1 FROM catalog_bootstrap WHERE id=? AND stage=? AND cursor=? AND lease_token=?)',args:[gate.id,gate.stage,gate.cursor,gate.token]}:{sql:'1',args:[]};}
function insertRows(database:D1Database,table:string,rows:any[],gate?:BootstrapGate,expected:any[]=[],scoreOnly=false){if(!rows.length)return null;const cols=rowTables[table],g=gateSql(gate);if(table==='catalog_games'&&scoreOnly)g.sql+=" AND EXISTS(SELECT 1 FROM catalog_games current WHERE current.id=json_extract(incoming.value,'$.id') AND current.content_hash=json_extract(incoming.value,'$.previous_hash'))";if(table!=='catalog_games'&&cols.includes('game_id')){g.sql+=" AND EXISTS(SELECT 1 FROM catalog_games cg JOIN json_each(?) expected ON cg.id=json_extract(expected.value,'$.id') AND cg.content_hash=json_extract(expected.value,'$.hash') WHERE cg.id=json_extract(incoming.value,'$.game_id'))";g.args.push(JSON.stringify(expected));}let conflict='ON CONFLICT DO NOTHING';if(table==='catalog_games')conflict=`ON CONFLICT(id) DO UPDATE SET ${cols.filter(c=>!['id','revision'].includes(c)).map(c=>`${c}=excluded.${c}`).join(',')},revision=catalog_games.revision+1 WHERE excluded.source_priority>=catalog_games.source_priority AND excluded.content_hash<>catalog_games.content_hash`;if(table==='catalog_source_ids')conflict='ON CONFLICT(source,external_id) DO UPDATE SET game_id=CASE WHEN catalog_source_ids.game_id=excluded.game_id THEN excluded.game_id ELSE NULL END';if(table==='catalog_scores')conflict='ON CONFLICT(record_id) DO UPDATE SET game_id=CASE WHEN catalog_scores.game_id=excluded.game_id THEN excluded.game_id ELSE NULL END,value=excluded.value,rating_count=excluded.rating_count,score_date=excluded.score_date,retrieved_at=excluded.retrieved_at,payload=excluded.payload';return database.prepare(`INSERT INTO ${table}(${cols.join(',')}) SELECT ${cols.map(c=>`json_extract(incoming.value,'$.${c}')`).join(',')} FROM json_each(?) incoming WHERE ${g.sql} ${conflict}`).bind(JSON.stringify(rows),...g.args);}
async function existingRows(database:D1Database,ids:string[]){if(!ids.length)return [];return (await database.prepare('SELECT id,payload,base_payload,source_priority,sort_order,content_hash,status FROM catalog_games WHERE id IN (SELECT value FROM json_each(?))').bind(JSON.stringify(ids)).all<any>()).results;}
export async function updateProjection(database:D1Database,game:CatalogGame,options:IngestOptions={}){return ingestGames(database,[game],options);}
/** Indexed identity checks, touched-game projection replacement and optional old-code mirror form one transaction. */
export async function ingestGames(database:D1Database,input:CatalogGame[],options:IngestOptions={}){
 await ensureGameplaySchema(database);
 if(input.length>100)throw new Error('Katalog yazımı en çok 100 oyunluk parçalarla yapılır.');if(new Set(input.map(g=>g.id)).size!==input.length||input.some(g=>!validCatalogGame(g)))throw new Error('Katalog oyun kaydı geçersiz.');
 const old=new Map((await existingRows(database,input.map(g=>g.id))).map(r=>[r.id,r]));
 const overrides=(await database.prepare('SELECT game_id,field,value FROM catalog_overrides WHERE game_id IN (SELECT value FROM json_each(?))').bind(JSON.stringify(input.map(g=>g.id))).all<any>()).results;
 const prepared=input.map(incoming=>{const previous=old.get(incoming.id);if(options.scoreOnly&&!previous)throw new Error('Puan aktarımı yeni oyun oluşturamaz.');const originalBase=JSON.parse(previous?.base_payload||previous?.payload||'{}');const base=options.scoreOnly?{...originalBase,metacriticUser:incoming.metacriticUser}:{...originalBase,...incoming};if(options.scoreOnly&&incoming.steamAppId!==originalBase.steamAppId)throw new Error('Puan aktarımının mağaza kimliği uyuşmuyor.');if(previous){const original=JSON.parse(previous.base_payload||previous.payload);if(original.steamAppId&&base.steamAppId!==original.steamAppId)throw new Error('Oyun veya sürüm kaynak kimliği değiştirilemez.');}if(!options.scoreOnly)Object.assign(base,preserveSteamReviewHistory(originalBase,incoming,base.steamAppId),preserveGameplay(originalBase,incoming,base.steamAppId));return {base,game:applyOverrides(projectionDefaults(base),overrides.filter(o=>o.game_id===incoming.id))};});
 const aliases=prepared.flatMap(({game:g})=>[...(g.steamAppId?[{source:'steam',external_id:String(g.steamAppId),game_id:g.id}]:[]),...(g.qid?[{source:'wikidata',external_id:g.qid,game_id:g.id}]:[]),...(validScore(g.metacriticUser)?[{source:'metacritic',external_id:g.metacriticUser.metacriticId+':'+(g.metacriticUser.platform??'unknown'),game_id:g.id},{source:'metacritic-record',external_id:g.metacriticUser.recordId,game_id:g.id}]:[])]);
 const aliasOwners=new Map<string,string>();for(const a of aliases){const key=a.source+':'+a.external_id;if(aliasOwners.has(key)&&aliasOwners.get(key)!==a.game_id)throw new Error('Aynı kaynak kimliği farklı oyunlara bağlanamaz.');aliasOwners.set(key,a.game_id);}
 const matched=(await database.prepare("SELECT s.source,s.external_id,s.game_id FROM catalog_source_ids s JOIN json_each(?) j ON s.source=json_extract(j.value,'$.source') AND s.external_id=json_extract(j.value,'$.external_id')").bind(JSON.stringify(aliases)).all<any>()).results;
 for(const found of matched)if(aliases.some(a=>a.source===found.source&&a.external_id===found.external_id&&a.game_id!==found.game_id))throw new Error('Kaynak kimliği başka bir oyun veya sürüme bağlı: '+found.source+':'+found.external_id);
 const rows:Record<string,any[]>={};for(const table of Object.keys(rowTables))rows[table]=[];const stamp=new Date().toISOString();const touched:string[]=[],result:CatalogGame[]=[],legacy:any[]=[];
 const oldTagIds=options.scoreOnly?[]:(await database.prepare('SELECT DISTINCT tag_id FROM catalog_game_tags WHERE game_id IN (SELECT value FROM json_each(?))').bind(JSON.stringify(input.map(g=>g.id))).all<any>()).results.map(r=>r.tag_id);
 for(const [offset,entry]of prepared.entries()){
  const incoming=entry.game;
  const previous=old.get(incoming.id);const priority=options.scoreOnly?(previous?.source_priority??30):(options.priority??30);if(previous&&previous.source_priority>priority)continue;
  const g=entry.game;const status=options.scoreOnly&&previous?previous.status:!g.platforms.includes('PC')?'archived':options.status??(g.catalogScope==='archive'?'archived':'published');const hash=await contentHash({base:entry.base,game:g,status});result.push(g);if(previous?.content_hash===hash)continue;touched.push(g.id);
  const score=validScore(g.metacriticUser),editionId=g.id+':pc:default';
  rows.catalog_games.push({previous_hash:previous?.content_hash??null,id:g.id,status,name:g.name,name_search:normalizeSearch(g.name),year:Number.isInteger(g.year)?g.year:null,steam_app_id:g.steamAppId||null,studio:g.studio||'',payload:JSON.stringify(g),base_payload:JSON.stringify(entry.base),content_hash:hash,score_value:score?score.score:null,score_count:scoreCount(score),score_date:score?.scoreDate??null,score_platform:score?.platform??null,catalog_added_at:g.catalogAddedAt??null,sort_order:previous?.sort_order??((options.sortOrder??0)+offset),revision:1,source_priority:priority,updated_at:stamp,mood:g.mood??g.editorial?.mood??null,steam_positive_percent:Number.isFinite(g.steamReview?.positivePercent)?g.steamReview.positivePercent:null,has_turkish:typeof g.hasTurkish==='boolean'?Number(g.hasTurkish):null,has_coop:typeof g.hasCoop==='boolean'?Number(g.hasCoop):null,cover_present:g.coverUrl?1:0,tag_profile_complete:normalizedTags(g).length?(g.steamTags.complete===false?0:1):null});
  rows.catalog_editions.push({id:editionId,game_id:g.id,edition_key:'pc:default',platform:'PC',payload:JSON.stringify({gameId:g.id,editionKey:'pc:default',platform:'PC',steamAppId:g.steamAppId??null})});
  if(g.steamAppId)rows.catalog_source_ids.push({source:'steam',external_id:String(g.steamAppId),game_id:g.id,edition_id:editionId,source_url:g.steamUrl||g.sourceUrl||null,retrieved_at:g.sourceRetrievedAt||null});
  if(g.qid)rows.catalog_source_ids.push({source:'wikidata',external_id:g.qid,game_id:g.id,edition_id:null,source_url:'https://www.wikidata.org/wiki/'+g.qid,retrieved_at:g.sourceRetrievedAt||null});
  if(score){rows.catalog_source_ids.push({source:'metacritic-record',external_id:score.recordId,game_id:g.id,edition_id:score.platform==='PC'?editionId:null,source_url:score.url,retrieved_at:score.snapshotDate??null});const scoreEdition=score.platform==='PC'?editionId:null;rows.catalog_scores.push({record_id:score.recordId,game_id:g.id,edition_id:scoreEdition,metric:score.metric,value:score.score,platform:score.platform??null,rating_count:scoreCount(score),score_date:score.scoreDate??null,retrieved_at:score.retrievedAt??score.snapshotDate??null,source_url:score.sourceUrl??score.url??null,payload:JSON.stringify(score)});rows.catalog_source_ids.push({source:'metacritic',external_id:score.metacriticId+':'+(score.platform??'unknown'),game_id:g.id,edition_id:scoreEdition,source_url:score.url,retrieved_at:score.snapshotDate??null});}
  for(const name of [...new Set(g.genres)]){const id=normalizeSearch(name);rows.catalog_genres.push({id,name});rows.catalog_game_genres.push({game_id:g.id,genre_id:id});}
  for(const [rank,t]of normalizedTags(g).entries())if(Number.isSafeInteger(t.id)&&t.id>0&&typeof t.name==='string'){rows.catalog_tags.push({id:t.id,name:t.name,label:options.labels?.[String(t.id)]||t.name});rows.catalog_game_tags.push({game_id:g.id,tag_id:t.id,weight:Number.isFinite(t.count)&&t.count>=0?t.count:null,rank});}
  for(const system of [...new Set(g.pcSystems||[])])if(['Windows','macOS','Linux'].includes(String(system)))rows.catalog_game_systems.push({game_id:g.id,system});
  for(const feature of gameplayKeys(g))rows.catalog_game_features.push({game_id:g.id,feature,source:g.gameplay.sourceKind,retrieved_at:g.gameplay.retrievedAt});
  for(const platform of [...new Set(g.platforms)])rows.catalog_game_platforms.push({game_id:g.id,platform});
  for(const token of searchTokens(g))rows.catalog_search_terms.push({token,game_id:g.id});rows.catalog_media.push(...normalizedMedia(g));
  if(options.writeLegacy)legacy.push({id:g.id,qid:g.qid||'steam:'+g.steamAppId,payload:JSON.stringify(g),fetched_at:stamp});
 }
 const statements:D1PreparedStatement[]=[],guard=gateSql(options.gate);
 const expected=rows.catalog_games.map(g=>({id:g.id,hash:g.content_hash}));
 const put=(table:string)=>{const statement=insertRows(database,table,rows[table],options.gate,expected,options.scoreOnly);if(statement)statements.push(statement);};put('catalog_games');
 // Deletes and replacements are atomic. This guard also rejects a stale bootstrap lease.
 const ids=JSON.stringify(expected);for(const table of ['catalog_game_features','catalog_game_genres','catalog_game_tags','catalog_game_systems','catalog_game_platforms','catalog_search_terms','catalog_media'])if(touched.length&&!options.scoreOnly)statements.push(database.prepare(`DELETE FROM ${table} WHERE game_id IN (SELECT cg.id FROM catalog_games cg JOIN json_each(?) expected ON cg.id=json_extract(expected.value,'$.id') AND cg.content_hash=json_extract(expected.value,'$.hash')) AND ${guard.sql}`).bind(ids,...guard.args));
 for(const table of Object.keys(rowTables).filter(t=>t!=='catalog_games'&&(!options.scoreOnly||['catalog_scores','catalog_source_ids'].includes(t))))put(table);
 const tagIds=[...new Set([...oldTagIds,...rows.catalog_tags.map(t=>t.id)])];if(touched.length){if(!options.scoreOnly)statements.push(database.prepare(`UPDATE catalog_tags SET game_count=(SELECT COUNT(*) FROM catalog_game_tags gt JOIN catalog_games cg ON cg.id=gt.game_id WHERE gt.tag_id=catalog_tags.id AND cg.status='published') WHERE id IN (SELECT value FROM json_each(?)) AND ${guard.sql}`).bind(JSON.stringify(tagIds),...guard.args));statements.push(database.prepare(`INSERT INTO catalog_meta(id,value,updated_at) SELECT 'revision','1',? WHERE ${guard.sql} ON CONFLICT(id) DO UPDATE SET value=CAST(CAST(catalog_meta.value AS INTEGER)+1 AS TEXT),updated_at=excluded.updated_at`).bind(stamp,...guard.args));}
 if(legacy.length)statements.push(database.prepare(`INSERT INTO source_games(id,qid,payload,fetched_at) SELECT json_extract(value,'$.id'),json_extract(value,'$.qid'),json_extract(value,'$.payload'),json_extract(value,'$.fetched_at') FROM json_each(?) legacy WHERE ${guard.sql} AND EXISTS(SELECT 1 FROM catalog_games cg JOIN json_each(?) expected ON cg.id=json_extract(expected.value,'$.id') AND cg.content_hash=json_extract(expected.value,'$.hash') WHERE cg.id=json_extract(legacy.value,'$.id')) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at`).bind(JSON.stringify(legacy),...guard.args,ids));
 statements.push(...(options.tail||[]));if(statements.length)await database.batch(statements);return {updated:touched.length,games:result,statements:statements.length};
}
