export type CatalogGame={id:string;name:string;steamAppId?:number|null;qid?:string;platforms:string[];genres:string[];[key:string]:any};
export function normalizeSearch(value:unknown):string{return String(value??'').toLocaleLowerCase('tr-TR').replace(/ı/g,'i').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim().replace(/\s+/g,' ');}
export function normalizedTags(game:CatalogGame){const profile=game.steamTags;if(!profile||profile.steamAppId!==game.steamAppId||normalizeSearch(profile.identityTitle)!==normalizeSearch(game.name)||!Array.isArray(profile.tags))return [];const seen=new Set<number>();return profile.tags.filter((tag:any)=>{if(!Number.isSafeInteger(tag.id)||tag.id<1||typeof tag.name!=='string'||!tag.name.trim()||seen.has(tag.id))return false;seen.add(tag.id);return true;}).sort((a:any,b:any)=>(Number.isFinite(b.count)?b.count:-1)-(Number.isFinite(a.count)?a.count:-1)).slice(0,20);}
export function searchTokens(game:CatalogGame){const text=[game.name,game.studio,...game.genres,game.discoveryHook,game.discoveryBody,game.desc,game.long,game.editorial?.desc,game.editorial?.long,...normalizedTags(game).map((x:any)=>x.name)].filter(Boolean).join(' ');return [...new Set(normalizeSearch(text).split(' ').filter(t=>t.length>0))].slice(0,512);}
export function validCatalogGame(g:any):g is CatalogGame{return /^[a-z0-9][a-z0-9-]{0,99}$/.test(g?.id||'')&&typeof g.name==='string'&&g.name.trim().length>0&&g.name.length<=500&&Array.isArray(g.platforms)&&Array.isArray(g.genres)&&(!g.steamAppId||Number.isSafeInteger(g.steamAppId)&&g.steamAppId>0)&&(!g.qid||/^Q\d+$/.test(g.qid));}
export function scoreCount(score:any):number|null{for(const value of [score?.userRatings,score?.ratingCount,score?.userCount,score?.reviewCount,score?.count])if(Number.isSafeInteger(value)&&value>=0)return value;return null;}
export function validScore(score:any){return score&&typeof score.recordId==='string'&&score.metric==='user-score'&&Number.isFinite(score.score)&&score.score>=0&&score.score<=10?score:null;}
export function projectionDefaults(game:CatalogGame){const genres=game.genres;const mood=game.mood??game.editorial?.mood??(genres.some(g=>['Strateji','Bulmaca'].includes(g))?'think':genres.some(g=>['Simülasyon','Yarış','Spor'].includes(g))?'relax':genres.some(g=>['Platform','Roguelike','Korku','Nişancı'].includes(g))?'challenge':genres.some(g=>['Açık dünya','Hayatta kalma'].includes(g))?'world':genres.some(g=>['RPG','Macera'].includes(g))?'story':'challenge');const desc=game.desc||game.editorial?.desc||game.discoveryHook||game.publisherDescription||'Bu oyuna henüz tanıtım eklenmemiş.';return {...game,mood,desc,long:game.long||game.editorial?.long||game.discoveryBody||game.publisherDescription||desc};}
export const protectedOverrideFields=new Set(['id','qid','steamAppId','sourceType','metacriticUser']);
export function applyOverrides(game:CatalogGame,overrides:{field:string;value:string}[]){const result={...game};for(const item of overrides){if(protectedOverrideFields.has(item.field)||item.field.includes('.')||['__proto__','constructor','prototype'].includes(item.field))continue;try{result[item.field]=JSON.parse(item.value);}catch{throw new Error('Manuel alan kaydı geçersiz JSON: '+game.id+'/'+item.field);}}if(!validCatalogGame(result))throw new Error('Manuel alan kaydı oyun kimliğini bozuyor.');return result;}
function https(value:any){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
export function normalizedMedia(g:CatalogGame){const out:any[]=[];const add=(kind:string,id:string,url:any,position:number,payload:any)=>{const safe=https(url);if(safe&&!out.some(x=>x.media_id===id))out.push({game_id:g.id,media_id:id,kind,url:safe,position,source:payload?.source||g.coverSource||g.sourceKind||null,retrieved_at:payload?.retrievedAt||g.sourceRetrievedAt||null,payload:JSON.stringify(payload)});};add('cover','cover',g.coverUrl,0,{url:g.coverUrl});add('cover','cover-fallback',g.coverFallbackUrl,1,{url:g.coverFallbackUrl});for(const [i,m]of (g.media?.items||g.media||g.screenshots||[]).entries?.()||[])add(m.kind||m.type||'image','media-'+(m.id??i),m.url||m.path_full||m.src,i+2,m);for(const [i,m]of (g.movies||[]).entries())add('video','movie-'+(m.id??i),m.url||m.mp4?.max||m.webm?.max,i+100,m);return out;}
export async function contentHash(value:unknown){const bytes=new TextEncoder().encode(JSON.stringify(value));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');}
