import seed from '../data/catalog.json';import archived from '../data/legacy-catalog.json';import scores from '../data/metacritic-users.json';import gameIdentities from '../data/game-identities.json';import tagProfiles from '../data/steam-tags.json';import tagLabels from '../data/steam-tag-labels.json';import {metacriticScoreForGame} from './metacritic-identity.mjs';import {steamGame} from './steam';import {db} from './db';import {safeUrl} from './security';
export type Game={id:string;qid?:string;steamAppId?:number|null;name:string;year:number|null;genres:string[];platforms:string[];studio?:string;url?:string;sourceUrl:string;sourceRetrievedAt:string;[key:string]:any};
const cachedId='wikidata-v1';const month=30*24*3600*1000;
export function unique<T>(xs:T[]){return [...new Set(xs)];}
function value(e:any,p:string){return (e?.claims?.[p]||[]).filter((c:any)=>c.rank!=='deprecated'&&c.mainsnak?.snaktype==='value').map((c:any)=>c.mainsnak.datavalue.value);}
function entityIds(e:any,p:string):string[]{return value(e,p).map((v:any)=>v.id).filter((v:any)=>/^Q\d+$/.test(v));}
function english(e:any){return e?.labels?.en?.value||e?.labels?.mul?.value||e?.labels?.tr?.value||'';}
export function platformName(label:string){const x=label.toLowerCase();if(/windows|linux|macos|os x|personal computer/.test(x))return 'PC';if(x.includes('playstation'))return 'PlayStation';if(x.includes('xbox'))return 'Xbox';if(x.includes('nintendo switch'))return 'Switch';if(x==='android')return 'Android';if(x==='ios'||x==='ipados')return 'iOS';return null;}
export function genreName(label:string){const x=label.toLowerCase();if(/role-playing|role playing/.test(x))return 'RPG';if(/survival/.test(x))return 'Hayatta kalma';if(/strategy|tactics|tactical/.test(x))return 'Strateji';if(/platform|metroidvania/.test(x))return 'Platform';if(/puzzle/.test(x))return 'Bulmaca';if(/adventure/.test(x))return 'Macera';if(/simulation|simulator|farm life/.test(x))return 'Simülasyon';if(/racing/.test(x))return 'Yarış';if(/sport/.test(x))return 'Spor';if(/shooter|first-person|third-person/.test(x))return 'Nişancı';if(/action|fighting|hack and slash/.test(x))return 'Aksiyon';if(/open.world|sandbox/.test(x))return 'Açık dünya';if(/horror/.test(x))return 'Korku';if(/roguelike|roguelite/.test(x))return 'Roguelike';return null;}
async function api(ids:string[],props:string){const url=new URL('https://www.wikidata.org/w/api.php');url.search=new URLSearchParams({action:'wbgetentities',ids:ids.join('|'),props,languages:'en|tr|mul',format:'json'}).toString();const r=await fetch(url,{headers:{'User-Agent':'NeOynasam/1.0 (open game discovery; CC0 data)'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`Kaynak HTTP ${r.status}`);const data:any=await r.json();if(data.error||!data.entities)throw new Error('Kaynak geçerli veri döndürmedi.');return data.entities;}
export async function cached(){try{const c=await db().prepare('SELECT payload,fetched_at AS fetchedAt FROM catalog_cache WHERE id=?').bind(cachedId).first<{payload:string;fetchedAt:string}>();if(c){const payload=JSON.parse(c.payload);return {games:payload.games as Game[],fetchedAt:c.fetchedAt,lastBatch:payload.lastBatch as number};}}catch{}return null;}
function validRecord(g:any){return /^[a-z0-9][a-z0-9-]{0,99}$/.test(g?.id||'')&&typeof g.name==='string'&&Array.isArray(g.platforms)&&Array.isArray(g.genres)&&( /^Q\d+$/.test(g.qid||'')||Number.isSafeInteger(g.steamAppId)&&g.steamAppId>0);}
const tagIdentity=(s:string)=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
function applyScore(g:Game):Game{const key=String(g.steamAppId);const profiles=[g.steamTags,(tagProfiles as Record<string,any>)[key]].filter(p=>p&&p.steamAppId===g.steamAppId&&tagIdentity(p.identityTitle||'')===tagIdentity(g.name)&&Array.isArray(p.tags)&&p.tags.length).sort((a,b)=>Date.parse(b.sourceKind==='steamdb-snapshot'?b.snapshotDate:b.retrievedAt)-Date.parse(a.sourceKind==='steamdb-snapshot'?a.snapshotDate:a.retrievedAt));return {...g,steamTags:profiles[0]||null,metacriticUser:metacriticScoreForGame(g,gameIdentities,scores)};}
export async function catalog(){const c=await cached();const map=new Map((seed as Game[]).map(g=>[g.id,g]));const old=new Map((archived as Game[]).map(g=>[g.id,g]));try{const rows=await db().prepare('SELECT payload FROM source_games ORDER BY id').all<{payload:string}>();for(const row of rows.results){const g=JSON.parse(row.payload) as Game;if(validRecord(g)){const target=g.platforms.includes('PC')&&(!old.has(g.id)||g.coverUrl)?map:old;const base=map.get(g.id)||old.get(g.id);target.set(g.id,{...base,...g});if(target===map)old.delete(g.id);}}}catch{}return {steamTagLabels:tagLabels,games:[...map.values()].filter(g=>g.platforms.includes('PC')).map(applyScore),archivedGames:[...old.values()].map(applyScore),fetchedAt:c?.fetchedAt||null,lastBatch:c?.lastBatch??-1};}
export async function knownGame(id:string){if(([...seed,...archived] as Game[]).some(g=>g.id===id))return true;try{return !!await db().prepare('SELECT id FROM source_games WHERE id=?').bind(id).first();}catch{return false;}}
export async function refreshSelected(ids:string[]){const all=await catalog();const selected=ids.map(id=>all.games.find(g=>g.id===id)).filter((g):g is Game=>!!g&&Number.isSafeInteger(g.steamAppId));if(!selected.length)throw new Error('Bu kayıtlarda yenilenebilir Steam oyunu yok.');const changed:Game[]=[];const failed:string[]=[];for(const g of selected){try{const patch=await steamGame(Number(g.steamAppId));changed.push({...g,...patch,platforms:unique(['PC',...g.platforms]),url:patch.steamUrl} as Game);}catch{failed.push(g.id);}}if(!changed.length)throw new Error('Steam yanıt vermedi; mevcut katalog korunuyor.');const stamp=new Date().toISOString();await db().batch([...changed.map(g=>db().prepare('INSERT INTO source_games(id,qid,payload,fetched_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at').bind(g.id,g.qid||'steam:'+g.steamAppId,JSON.stringify(g),stamp)),db().prepare('INSERT INTO catalog_cache(id,payload,fetched_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at').bind(cachedId,JSON.stringify({lastBatch:-1}),stamp)]);return {updated:changed.length,games:changed.map(applyScore),failed,fetchedAt:stamp};}
export async function metadataForQids(qids:string[]){const entities=await api(qids,'claims|labels');const accepted=qids.filter(qid=>entityIds(entities[qid],'P31').includes('Q7889'));const ids=unique(accepted.flatMap(qid=>['P400','P136','P178','P404'].flatMap(p=>entityIds(entities[qid],p))));const labels:any={};for(let i=0;i<ids.length;i+=50)Object.assign(labels,await api(ids.slice(i,i+50),'labels'));return accepted.map(qid=>{const e=entities[qid];const dates=value(e,'P577').filter((v:any)=>v.precision>=9&&/^\+\d{4}-/.test(v.time)).map((v:any)=>Number(v.time.slice(1,5))).filter((y:number)=>y>=1970&&y<=new Date().getUTCFullYear());const genresRaw=entityIds(e,'P136').map(id=>english(labels[id])).filter(Boolean);const platformsRaw=entityIds(e,'P400').map(id=>english(labels[id])).filter(Boolean);return {id:'game-'+qid.toLowerCase(),qid,steamAppId:Number(value(e,'P1733').find((v:any)=>/^\d+$/.test(v)))||null,name:english(e),year:dates.length?Math.min(...dates):null,genres:unique(genresRaw.map(genreName).filter(Boolean)) as string[],platforms:unique(platformsRaw.map(platformName).filter(Boolean)) as string[],studio:entityIds(e,'P178').map(id=>english(labels[id])).filter(Boolean).join(', '),url:value(e,'P856').map(safeUrl).find(Boolean)||'',genresRaw,platformsRaw,modeRaw:entityIds(e,'P404').map(id=>english(labels[id])).filter(Boolean),sourceUrl:`https://www.wikidata.org/wiki/${qid}`,sourceRetrievedAt:new Date().toISOString().slice(0,10),yearSource:'Earliest non-deprecated publication year; can include early access'} as Game;}).filter(g=>g.name);}
export async function sourceSearch(query:string){const url=new URL('https://www.wikidata.org/w/api.php');url.search=new URLSearchParams({action:'wbsearchentities',search:query,language:'en',uselang:'en',type:'item',limit:'10',format:'json'}).toString();const response=await fetch(url,{headers:{'User-Agent':'NeOynasam/1.0 (CC0 game discovery)'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('Kaynağa ulaşılamadı.');const result:any=await response.json();const ids=(result.search||[]).map((r:any)=>r.id).filter((id:string)=>/^Q\d+$/.test(id));if(!ids.length)return [];return (await metadataForQids(ids)).filter(g=>g.platforms.includes('PC'));}
export async function addSourceGame(qid:string){const c=await catalog();const existing=c.games.find(g=>g.qid===qid);if(existing)return existing;if(c.games.length>=5000)throw new Error('Katalog sınırına ulaşıldı.');const records=await metadataForQids([qid]);if(!records.length||!records[0].platforms.includes('PC'))throw new Error('Yayımlanmış bir PC oyunu doğrulanamadı.');let game=records[0];if(game.steamAppId){const same=c.games.find(g=>g.steamAppId===game.steamAppId);if(same)return same;const patch=await steamGame(Number(game.steamAppId));game={...game,...patch,id:game.id,qid,platforms:game.platforms,url:patch.steamUrl} as Game;}const stamp=new Date().toISOString();game={...game,catalogAddedAt:stamp};await db().prepare('INSERT INTO source_games(id,qid,payload,fetched_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at').bind(game.id,game.qid,JSON.stringify(game),stamp).run();return applyScore(game);}
