import { sqliteTable,text,integer,real,primaryKey,index,uniqueIndex } from 'drizzle-orm/sqlite-core';
export const library=sqliteTable('library',{userId:text('user_id').notNull(),gameId:text('game_id').notNull(),status:text('status').notNull().default('planned'),note:text('note').notNull().default(''),rating:integer('rating'),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.userId,t.gameId]}),index('library_user_idx').on(t.userId)]);
export const lists=sqliteTable('lists',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),createdAt:text('created_at').notNull()},t=>[index('lists_user_idx').on(t.userId)]);
export const listGames=sqliteTable('list_games',{listId:text('list_id').notNull(),gameId:text('game_id').notNull()},t=>[primaryKey({columns:[t.listId,t.gameId]})]);
export const views=sqliteTable('game_views',{gameId:text('game_id').primaryKey(),count:integer('count').notNull().default(0)});
export const viewVisits=sqliteTable('view_visits',{gameId:text('game_id').notNull(),viewer:text('viewer').notNull(),day:text('day').notNull()},t=>[primaryKey({columns:[t.gameId,t.viewer,t.day]})]);
export const catalogCache=sqliteTable('catalog_cache',{id:text('id').primaryKey(),payload:text('payload').notNull(),fetchedAt:text('fetched_at').notNull()});
export const sourceGames=sqliteTable('source_games',{id:text('id').primaryKey(),qid:text('qid').notNull().unique(),payload:text('payload').notNull(),fetchedAt:text('fetched_at').notNull()});

// Additive catalog projection. The original public ID is never regenerated from a title.
export const catalogGames=sqliteTable('catalog_games',{
 id:text('id').primaryKey(),status:text('status').notNull(),name:text('name').notNull(),nameSearch:text('name_search').notNull(),year:integer('year'),steamAppId:integer('steam_app_id'),studio:text('studio').notNull().default(''),payload:text('payload').notNull(),basePayload:text('base_payload').notNull().default('{}'),contentHash:text('content_hash').notNull(),scoreValue:real('score_value'),scoreCount:integer('score_count'),scoreDate:text('score_date'),scorePlatform:text('score_platform'),catalogAddedAt:text('catalog_added_at'),sortOrder:integer('sort_order').notNull().default(0),revision:integer('revision').notNull().default(1),sourcePriority:integer('source_priority').notNull().default(10),updatedAt:text('updated_at').notNull(),mood:text('mood'),steamPositivePercent:real('steam_positive_percent'),hasTurkish:integer('has_turkish'),hasCoop:integer('has_coop'),coverPresent:integer('cover_present').notNull().default(0),tagProfileComplete:integer('tag_profile_complete')
},t=>[uniqueIndex('catalog_games_steam_idx').on(t.steamAppId),index('catalog_games_status_order_idx').on(t.status,t.sortOrder,t.id),index('catalog_games_name_idx').on(t.status,t.nameSearch,t.id),index('catalog_games_year_idx').on(t.status,t.year,t.id),index('catalog_games_score_idx').on(t.status,t.scoreValue,t.id),index('catalog_games_added_idx').on(t.status,t.catalogAddedAt,t.id),index('catalog_games_mood_idx').on(t.status,t.mood,t.id),index('catalog_games_steam_review_idx').on(t.status,t.steamPositivePercent,t.id),index('catalog_games_turkish_idx').on(t.status,t.hasTurkish,t.id),index('catalog_games_coop_idx').on(t.status,t.hasCoop,t.id)]);
export const catalogEditions=sqliteTable('catalog_editions',{id:text('id').primaryKey(),gameId:text('game_id').notNull(),editionKey:text('edition_key').notNull(),platform:text('platform'),payload:text('payload').notNull()},t=>[uniqueIndex('catalog_editions_identity_idx').on(t.gameId,t.editionKey),index('catalog_editions_game_idx').on(t.gameId)]);
export const catalogSourceIds=sqliteTable('catalog_source_ids',{source:text('source').notNull(),externalId:text('external_id').notNull(),gameId:text('game_id').notNull(),editionId:text('edition_id'),sourceUrl:text('source_url'),retrievedAt:text('retrieved_at')},t=>[primaryKey({columns:[t.source,t.externalId]}),index('catalog_source_ids_game_idx').on(t.gameId)]);
export const catalogScores=sqliteTable('catalog_scores',{recordId:text('record_id').primaryKey(),gameId:text('game_id').notNull(),editionId:text('edition_id'),metric:text('metric').notNull(),value:real('value'),platform:text('platform'),ratingCount:integer('rating_count'),scoreDate:text('score_date'),retrievedAt:text('retrieved_at'),sourceUrl:text('source_url'),payload:text('payload').notNull()},t=>[index('catalog_scores_game_idx').on(t.gameId,t.metric),index('catalog_scores_identity_idx').on(t.editionId,t.platform,t.metric)]);
export const catalogGenres=sqliteTable('catalog_genres',{id:text('id').primaryKey(),name:text('name').notNull()});
export const catalogGameGenres=sqliteTable('catalog_game_genres',{gameId:text('game_id').notNull(),genreId:text('genre_id').notNull()},t=>[primaryKey({columns:[t.gameId,t.genreId]}),index('catalog_game_genres_filter_idx').on(t.genreId,t.gameId)]);
export const catalogTags=sqliteTable('catalog_tags',{id:integer('id').primaryKey(),name:text('name').notNull(),label:text('label').notNull(),gameCount:integer('game_count').notNull().default(0)});
export const catalogGameTags=sqliteTable('catalog_game_tags',{gameId:text('game_id').notNull(),tagId:integer('tag_id').notNull(),weight:real('weight'),rank:integer('rank').notNull()},t=>[primaryKey({columns:[t.gameId,t.tagId]}),index('catalog_game_tags_filter_idx').on(t.tagId,t.gameId)]);
export const catalogGameSystems=sqliteTable('catalog_game_systems',{gameId:text('game_id').notNull(),system:text('system').notNull()},t=>[primaryKey({columns:[t.gameId,t.system]}),index('catalog_game_systems_filter_idx').on(t.system,t.gameId)]);
export const catalogGamePlatforms=sqliteTable('catalog_game_platforms',{gameId:text('game_id').notNull(),platform:text('platform').notNull()},t=>[primaryKey({columns:[t.gameId,t.platform]}),index('catalog_game_platforms_filter_idx').on(t.platform,t.gameId)]);
export const catalogSearchTerms=sqliteTable('catalog_search_terms',{token:text('token').notNull(),gameId:text('game_id').notNull()},t=>[primaryKey({columns:[t.token,t.gameId]}),index('catalog_search_terms_game_idx').on(t.gameId)]);
export const catalogMedia=sqliteTable('catalog_media',{gameId:text('game_id').notNull(),mediaId:text('media_id').notNull(),kind:text('kind').notNull(),url:text('url').notNull(),position:integer('position').notNull(),source:text('source'),retrievedAt:text('retrieved_at'),payload:text('payload').notNull()},t=>[primaryKey({columns:[t.gameId,t.mediaId]}),index('catalog_media_game_idx').on(t.gameId,t.position)]);
export const catalogOverrides=sqliteTable('catalog_overrides',{gameId:text('game_id').notNull(),field:text('field').notNull(),value:text('value').notNull(),updatedAt:text('updated_at').notNull(),updatedBy:text('updated_by')},t=>[primaryKey({columns:[t.gameId,t.field]})]);
export const catalogBootstrap=sqliteTable('catalog_bootstrap',{id:text('id').primaryKey(),stage:text('stage').notNull(),cursor:text('cursor').notNull().default('0'),processed:integer('processed').notNull().default(0),leaseToken:text('lease_token'),leaseUntil:text('lease_until'),updatedAt:text('updated_at').notNull()});
export const catalogMeta=sqliteTable('catalog_meta',{id:text('id').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});

export const catalogGameFeatures=sqliteTable('catalog_game_features',{gameId:text('game_id').notNull().references(()=>catalogGames.id,{onDelete:'cascade'}),feature:text('feature').notNull(),source:text('source'),retrievedAt:text('retrieved_at')},t=>[primaryKey({columns:[t.gameId,t.feature]}),index('catalog_game_features_filter_idx').on(t.feature,t.gameId)]);
